- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/next_steps.rst
- docs/source/overview.rst
- examples/getting_started.ipynb
- pyquil/forest.py
- pyquil/gates.py
- pyquil/parametric.py
- pyquil/paulis.py
- pyquil/quil.py
- pyquil/quil_atom.py
- pyquil/quilbase.py
Fixed some minor consistency- and clarity-related issues in the documentation, and updated the `getting_started.ipynb` notebook. The notebook now parallels the most recent iteration of the *Installation and Getting Started* page in the docs, and has a table of contents with internal anchor links.
> Minor cleanup for docs and getting_started jupyter notebook 

- pyquil/quilbase.py
- pyquil/tests/test_quil.py
This allows to extract the addresses of all qubits involved in a pyquil.Program and more generally an InstructionGroup object.
> Implemented `InstructionGroup.extract_qubits()`

- README.md
- pyquil/forest.py
- pyquil/gates.py
- pyquil/parametric.py
- pyquil/paulis.py
- pyquil/quil.py
- pyquil/quilbase.py
- pyquil/resource_manager.py
- pyquil/slot.py
Sphinx-style docstrings require a newline between the description section and the parameters/return value section of the docstrings for correct rendering. Also, parameter docstrings will correctly interpret types if they are in the form `:param param-type param-name: param-description` and return value docstrings can be typed by including an `:rtype: return-type` tag.
> Small fixes and improvements to the sphinx-style docstrings

- pyquil/quilbase.py
- pyquil/tests/test_quil.py
Based on the discussion on https://github.com/rigetticomputing/pyquil/issues/20 I implemented the unitary check.
> DefGate: validation for unitary matrix 

- docs/source/getting_started.rst
- examples/getting_started.ipynb
- pyquil/tests/test_quil.py
- setup.py
Removes scipy dep in the test for defgate.  Now directly specifies the
sqrt of x gate.
Minor clean up of documentation so x-xqrt-x gate now is the correct
tensor product ordering corresponding to a left most significant bit.
> Remove scipy dep and small code clean up

- pyquil/quilbase.py
Add a clarifying docstring about `inst` causing mutations. This caused a bug in the generation of programs for QAOA a few weeks back.
> add inst mutating docstring

- docs/source/getting_started.rst
- examples/getting_started.ipynb
Clean up two stray references to the former SciPy dependency, which was removed in f40fe11e238ff0f4b8d74d47a7471fdc3aa9da66.
> Follow up SciPy removal cleanup in documentation

- README.md
- setup.cfg
- setup.py
Changes:
- Integrate pytest with `python setup.py test`, as per [0].
- Document test dependencies (pytest and mock) and automate their setup when `python setup.py test` is run. i.e. if in a virtualenv.
[0] https://docs.pytest.org/en/latest/goodpractices.html
> Integrate pytest and be explicit about test dependencies

- pyquil/quil.py
- pyquil/tests/test_quil.py
It is useful to be able to take a list of pyquil programs and append them sequentially together into one program.  This can almost be done easily using the built-in `sum` method, except it produces a little bug if you don't remember that sum starts with a 0 that you need to change.
Adding a `merge_program` method so that:
```
merge_program([Program(X(0)), Program(Y(0))])
```
gives
```
X 0
Y 0
```
means that the library comes with a built in method with the expected behavior.
> add method to merge a list of pyquil programs

- docs/source/getting_started.rst
- docs/source/intro_to_qc.rst
- pyquil/forest.py
- pyquil/tests/test_forest.py
- pyquil/tests/test_wavefunction.py
- pyquil/wavefunction.py
This PR adds a wavefunction object that makes some useful utility functions for parsing wave-functions to be more human readable. 
```
from pyquil.quil import Program
import pyquil.forest as forest
from pyquil.gates import RX, CNOT
qvm = forest.Connection()
p = Program(RX(1.232, 0), CNOT(0,1), RX(3.02123, 1), RX(0.032, 0), CNOT(0,1))
wvf, _ = qvm.wavefunction(p)
wvf.pretty_print()
```
'(0.05+0.01j)|00> + (-0.01-0.03j)|01> + (-0-0.81j)|10> + (-0.58+0j)|11>'
```
wvf.pretty_print(decimal_digits=4)
```
'(0.0491+0.0092j)|00> + (-0.013-0.0347j)|01> + (-0.0006-0.8146j)|10> + (-0.5767-0.0008j)|11>'
```
from pyquil.forest import pretty_print_probabilities
wvf.pretty_print_probabilities()
```
{'10': 0.66, '11': 0.33}
```
wvf.pretty_print_probabilities(decimal_digits=4)
```
{'00': 0.0025, '01': …
> introduce a Wavefunction object

- examples/run_quil.py
More robust argument parsing.
Note that this slightly changes the usage of this script. The number of classical registers used to be a positional argument. Since it's optional, the unixy convention is to give it a flag. I chose `-n`. We can change it (back) to a simple positional argument if you'd prefer. 
Also sundry modifications to make it python 3 compatible: print function and explicit listification of `range`
> Modify run_quil.py to use argparse

- pyquil/paulis.py
Unitaries are generated by exponentiating antihermetian operators.  We
implicitly multiply a Pauli operators by 'i' to form an antihermetian matrix.
Therefore, we can only accept real coefficients.  We were checking for a
zero imaginary component but not making sure the coeff is
defined by a floating point--vs complex float.
> Real angles for exponentiating i*Pauliterms

- pyquil/paulis.py
- pyquil/tests/test_paulis.py
This branch makes a few improvements simplify working with pauli objects.
It adds the ability to subtract PauliTerm and PauliSum objects from each other and from constants, e.g.
```
from pyquil.paulis import sX
term = 2. - sX(0)
term = term - sY(1)
```
It adds the ability to index into PauliSums term by term, e.g.
```
pauli_sum = sX(0) + 0.5 * sX(1)
assert pauli_sum[0] == sX(0)
for ii, xx in enumerate(pauli_sum):
assert pauli_sum[ii] == xx
```
> Overload additional methods for Pauli objects

- pyquil/paulis.py
- pyquil/wavefunction.py
General clean up of some modules.
Paulis exponentiate needs to define
the terms coefficient as real so we don't write r + 01j into the quil
program.
Asserting that the amplitude vector is a power of 2 by bit AND.
Removing the numpy dependency in `wavefunction.py`
> Remove numpy, wf check power of 2, real coeffs

- pyquil/qpu.py
Endpoint for running on the QPU is currently different that the qvm api.
Upon import of QPUConnection or get_info from pyquil/qpu.py the ENDPOINT
is overwritten with the job/beta endpoint.
A QPUConnection object now updates the header files of the session to
allow access to the QPU.
> ENDPOINT Override HACK with Session Update

- docs/source/qpu.rst
Includes instructions on setting `QVM_URL=https://job.rigetti.com/beta` for QPU use.
> QVM_URL endpoint for QPU use

- pyquil/job_results.py
There was a change from Python3 to Python2 in how typecasting after numeric division works. For example:
- Python2.7
```
>>> type(1 / 2)
<type 'int'>
```
- Python3
```
>>> type(1 / 2)
<class 'float'>
```
The changes included in this PR make typecasting to int explicit where needed in `job_result.py` to be more compatible with Python3.
h/t to Andrew Guo for altering us to this
> bugfix to accomodate how python3 no longer returns an int after division

- pyquil/gates.py
- pyquil/quilbase.py
- pyquil/tests/test_quil.py
The docs suggest you should be able to do something like:
```python
mygate.get_constructor()(1)
```
This allows that by converting the int to a DirectQubit.
> Fix bug with DefGate#getConstructor()

- docs/source/getting_started.rst
Fixes #125 
This has come up as confusing a few times, c.f. #125 as another instance.  This clarifies the docs language for pyquil_config setup.
> clarify that the pyquil_config needs to be created

- README.md
- docs/source/getting_started.rst
- pyquil/api.py
- pyquil/config.py
- pyquil/qpu.py
- pyquil/setup/pyquil_config_setup.py
- pyquil/tests/test_qpu.py
- setup.py
Fixes issue #128
This does a number of things:
- improves the getting started guide to deal with problems frequently encountered by support
- fixes and improves the pyquil-config-setup script
- points users to use the pyquil-config-setup script instead of doing it themselves
- refactors config file parsing the QPUConnection object to be less global
Here's what a user seems when they try to open up a connection for the first time with no .pyquil_config file:
```
>>> from pyquil.api import SyncConnection
>>> SyncConnection()
! WARNING:
!   There was an issue finding your pyQuil config file.
!   Have you run the pyquil-config-setup command yet?
! See the getting started guide at https://go.rigetti.com/getting-started
```
Here's what they see if they forge on ahead anyway:
```
>>> …
```
> Refactor config and QPUConnection, better error messages

- pyquil/quilbase.py
This docstring was missing a newline after the description, so it wasn't properly rendered in the online documentation.
> pyquil.quilbase: fix docstring

- pyquil/slot.py
These lines get accidentally concatenated in the online docs.
> Add line blocks to docstring for Slot

- pyquil/paulis.py
- pyquil/tests/test_paulis.py
Rationale: see https://github.com/rigetticomputing/pyquil/pull/153#discussion_r146120458
> ID and ZERO: switch to be defined as a function instead

- pyquil/kraus.py
- pyquil/quil.py
- pyquil/quilbase.py
- pyquil/tests/test_quil.py
This implements the new `PRAGMA ADD-KRAUS <GATENAME> <QUBITS+> "(...)"` statements for noisy qvm simulations.
@stevenheidel maybe take a quick look, but even if it looks good let's discuss before merging.
> Added helper function to define noisy gates as Kraus maps

- pyquil/kraus.py
- pyquil/tests/test_quil.py
This fixes #176, a bug in the generation of `ADD-KRAUS` pragmas and also removes some unused code.
> Ensure that gate name is added to ADD-KRAUS args

- docs/source/getting_started.rst
- docs/source/intro_to_qc.rst
Since I found 4 different naming conventions for the `api.QVMConnection().wavefunction(p)` objects, I unified all of them into one to minimize the confusion among new users.
Old naming: `wvf`, `wavf`, `wavefunc`, `wavefunction`.
New naming: `wavefunction`.
I decided to use `wavefunction` because it's most clear and unambiguous.
> Unified naming of wavefunction variables in docs.

- docs/source/source_docs.rst
The generated source code documentation has two links to the paulis module documentation. I removed the first duplicate in order to preserve the alphabetical order of the modules in the table of contents listing.
> removed duplicate paulis documentation link

- docs/source/noise_models.rst
Sphinx docs don't render properly for the noise models, due to missing curly braces and latex code blocks.
> Fixing noise docs so they render properly

- docs/source/noise_models.rst
Fixes #229 
compare this with http://pyquil.readthedocs.io/en/latest/noise_models.html#adding-t1-and-t2-type-noise-to-all-your-gates
> Normalized rst code snippet directives in noise_models.rst

- pyquil/api/qpu.py
`get_devices()` returns a `KeyError` if the user has no QPU access. This PR parses and raises the `MissingPermissionsError`.
> parse error in get_devices

- pyquil/api/qvm.py
- pyquil/paulis.py
This lets you write a simpler function to compute expectations for Paulis
```python
def qvm_expectation(prep_program, hamiltonian, cxn):
progs, coefs = hamiltonian.get_programs()
expect_coeffs = np.array(cxn.expectation(prep_program, operator_programs=progs))
return np.real_if_close(np.dot(coefs, expect_coeffs))
```
cc #261 
see reverted commit b4cd63c in this PR where I started to hack the `QVMConnection.expectation()` method before realizing it was starting to get hairy.
> PauliSum helper functions for computing expectation

- pyquil/device.py
- pyquil/tests/test_device.py
KrausModel (and seed dicts) fixtures.
Create fixtures out of ARCH_QPU for dict and ISA object.
Renamed arch_qpu to isa, added device_raw and device_fixture fixtures, and test_device test.
device.raw -> ._raw, and ._isa/._noise_model -> .isa/.noise_model, and modifications to the docs.
Rebase issues
Fixed tests
pep8
> feature/device-class-enhancements (#275)

- pyquil/paulis.py
- pyquil/tests/test_paulis.py
Removes number of qubits input for the `commuting_set` method in
pyquil.paulis
> Remove dangling input from commuting_set method

- pyquil/api/_base_connection.py
- pyquil/api/job.py
`job.estimated_time_left_in_queue()` method, using an average roundtrip time of `3` seconds, and the current place in the queue. Modified queued job log message in `qpu.run_and_measure` to include time estimate. Resolves #298.
> job.estimated_time_left_in_queue() method, with use in QPU logging. Resolves #298.

- pyquil/noise.py
- pyquil/tests/test_noise.py
Currently applying an arbitrary noise model to a program expressed in the natural gateset is broken. This PR fixes this.
> Refactored apply_noise_model and helpers

- pyquil/api/compiler.py
- pyquil/api/qpu.py
- pyquil/api/qvm.py
- pyquil/tests/test_api.py
This commit allows a user to submit jobs with lower execution priority, suitable for those running continuous integration tests who do not want to block active users.
> add priority named argument to job submission routines

- pyquil/api/compiler.py
- pyquil/api/qpu.py
- pyquil/api/qvm.py
The previous PR had incorrect docstrings. Higher priority values mean faster execution, the opposite of `nice`.
> job prioritization round 2

- pyquil/paulis.py
- pyquil/tests/test_paulis.py
This fixes an annoying issue that crops up when constructing PauliTerm's with bespoke numpy integer type indices.
> Allow PauliTerm qubit indices to be numpy.int{8,16,32,64}

- pyquil/api/errors.py
- pyquil/api/job.py
Allows for better handling of quilc exceptions occurring during async endpoint usage.
(I'm a little surprised that the QVM sync endpoint has no special error handling in pyQuil—but that's a separate PR for a separate day.)
> introduce and use QUILCError

- docs/source/changes.rst
- docs/source/index.rst
- pyquil/paulis.py
- pyquil/quil.py
- pyquil/tests/test_parametric.py
- pyquil/tests/test_paulis.py
See changelog and #355 for motivation.
In particular, this will be important for using QubitPlaceholder's cc #354 as well as for tailoring pyquil programs to physical devices. 
This PR attempts to keep as much behavior the same as possible. Pay close attention to the changes in the tests for what behaviour changes. It should only be in cases where a string is being generated... either the str() of a paulisum or a program resulting from exponentiating a pualisum
> PauliTerms remember their qubit ordering

- docs/source/intro.rst
- docs/source/intro_to_qc.ipynb
I think it may be confusing to someone who is just getting into quantum computing.
Basically, H|0> isn't Bell state of two-qubit system.
> Fix typos by replacing H|0> with Bell state

- tox.ini
PyQuil 1.9 will not officially support Python 2. We can no longer spare the extra dev time to support this legacy platform. No purposefully breaking changes will be introduced in version 1.9 but we will not go out of our way to test for incompatibilities.
PyQuil 2 will use python-3-only features and will no longer support python2 even unofficially.
> Disable tests on Python 2

- pyquil/gates.py
Michael Campbell pointed out that the docstring for CPHASE (line 209) was outright incorrect. I fixed that, and I modified the other docstrings to be slightly more informative.
> Update CPHASE docstrings

- pyquil/quil.py
- pyquil/tests/test_quil.py
Resolves #223. If no qubit/register pairs are provided to `program.measure_all()`, all qubits are measured.
> program.measure_all() defaults to measuring all qubits.

- pyquil/api/qpu.py
- pyquil/api/qvm.py
- pyquil/quil.py
- pyquil/tests/test_api.py
- pyquil/tests/test_quil.py
Resolves #137. If the `.run` method for either the QVM or the QPU is not supplied a `classical_addresses` argument, a `get_classical_addresses_from_program` function will infer the classical addresses from the `MEASURE` instructions in the program.
> Default classical_addresses in qvm./qpu.run method

- examples/benchmarking_example.ipynb
- pyquil/api/compiler.py
- pyquil/paulis.py
- pyquil/tests/test_api.py
- pyquil/tests/test_paulis.py
@mpharrigan This PR is meant to provide functionality for conjugating `PauliTerms` by Clifford circuits, and generating randomized benchmarking sequences. Both of these target different endpoints than the compiler.
> Adding support for generating RB sequences and clifford conjugation

- pyquil/api/qvm.py
@mpharrigan I've updated the docs in qvm.py to try to help set users `expectation`s. 
I'm not sure standard practice for warnings, but I just spent some time trying to debug why I was getting the wrong answer, when I was giving it a program, and it was happily iterating over it and shipping off the line-by-line subprograms.
e.g. 
`qvm.expectation(Program("X 0\nY 1"))`
When what I really wanted was
`qvm.expectation([Program("X 0\nY 1"))`
Of course you can also tell from the length of the returned list, but I think warning the user is a good idea.
> doc improvements for expectation, and an added warning

- pyquil/api/qpu.py
When running e.g. a large QAOA job on the QPU the connection gets killed when the device gets retuned (which yields either a DeviceRetuning or DeviceOffline error) which means all the work until this point goes down the drain. This PR resolves the problem by excepting these two types of error.
> Excepting DeviceRetuning & DeviceOffline Errors

- pyquil/paulis.py
Changing document string to reflect what the exponential_map procedure is doing in an attempt to close this issue: https://github.com/rigetticomputing/pyquil/issues/322.
> Fix document string for the return type of exponential_map

- pyquil/api/job.py
Closes #400.
It's not clear to me how extensive this error forwarding should be among the other accessors on a Job object. I think it's fine to add this error handling in just this one place, but I invite advice.
> propagate Forest errors through Job.compiled_quil()

- pyquil/api/compiler.py
- pyquil/tests/test_api.py
The new randomized benchmarking routine does not always compose to the identity. In addition, it would be useful to have more/better documentation.
Both of these are addressed in this PR.
In addition, I've removed the qubits argument from RB. It seems redundant, given that the generating gateset should act on the same number of qubits that you want to benchmark. 
@mpharrigan - I know API changes are bad, but given that this feature is in its infancy, I think it's better to rethink the signature now, rather than later.
This is also something that likely would have been caught by tests, but we don't have a framework set up yet to test the QVM or Compiler from pyQuil, as we've discussed before.
> Randomized benchmarking does not always compose to the identity

- docs/source/basics.rst
Addressing this issue: https://github.com/rigetticomputing/pyquil/issues/435
`print` is added because the tutorial says ```The returned value should be: [[1]]```. It's more clear if the value is printed.
> Clearing up the instructions for the first program in the basics tutorial

- pyquil/quilatom.py
- pyquil/quilbase.py
- pyquil/tests/test_paulis_with_placeholders.py
- pyquil/tests/test_quil.py
```
RX(-pi) {q4632261800}
RZ(-pi/2) {q4632261800}
RX(-pi/2) {q4632261800}
RY(-pi/2) {q4632261800}
RX(-pi) {q4632261800}
RY(pi/2) {q4632261800}
RX(-pi/2) {q4632261800}
RY(pi/2) {q4632261800}
RY(-pi/2) {q4632261800}
RZ(-pi/2) {q4632261800}
RX(-pi/2) {q4632261800}
RZ(-pi/2) {q4632261800}
RX(-pi) {q4632261800}
RZ(pi/2) {q4632261800}
RX(-pi/2) {q4632261800}
RZ(pi/2) {q4632261800}
RX(pi/2) {q4632261800}
RX(-pi/2) {q4632261800}
RZ(pi/2) {q4632261800}
MEASURE {q4632261800} [0]
```
> Prettier str() representation of QubitPlaceholder and programs containing them

- pyquil/setup/pyquil_config_setup.py
> fix forest link in pyquil-config-setup instructions

- pyquil/api/compiler.py
The order of the returned cliffords was recently reversed (and I verified this gave the identity, I thought, on a handful of circuits.) It appears that the Clifford decompositions also need to be reversed. I verified that this worked on a handful of circuits returned, but I encourage reviewers to verify themselves so this doesn't happen again.
> Fixing cliffords again

- examples/quantum_die.py
When `n = 2^m`, quantum_die example returns an incorrect value. For example, in the case of `n = 8`, process_result(r) returns `0-7` because qubits length is 3. Therefore, this example returns `1-7`, never returns `8`. We have to add `1` to the process_result(r) value to get the correct value.
> Fix quantum_die example

- pyquil/magic.py
- pyquil/tests/test_magic.py
- requirements.txt
- setup.py
Allows you to write this:
```python
@magicquil
def fast_reset(q1):
reg1 = MEASURE(q1)
if reg1:
X(q1)
else:
I(q1)
my_program = fast_reset(0)  # this will be a Program object
```
Another example from @mpharrigan:
```python
@magicquil
def qaoa(reward: PauliSum, driver: PauliSum, p_steps: int):
for q in driver.get_qubits():
H(q)
betas = np.linspace(1, 0, p_steps)
gammas = np.linspace(0, 1, p_steps)
for beta, gamma in zip(betas, gammas):
for term in reward:
EXP(term, gamma)
for term in driver:
EXP(term, beta)
```
Read through the comments to explain how this is done through a combination of AST manipulation, context variables, and frame hacking.
- Inner functions don't work. There is an easy fix for this (just unindent the source lines before sending it to the parser) but I was too lazy.
- …
> Magic Quil Decorator

- pyquil/noise.py
- pyquil/tests/test_noise.py
As discussed with @mpharrigan and motivated by @ncrubin this corrects the conversion from "gate_time/coherence_time" to the actual error probability for a single gate.
> Improve error probability computation in  noise.damping_after_dephasing

- docs/source/basics.rst
- docs/source/modules.rst
This branch adds `pyquil.parser` autodoc information to the pyQuil docs, as well as a short demonstration of a `Program` constructor feature that uses the parser.
> Docs: reveal parser

- pyquil/api/job.py
Added two convenience functions `job.running_time()` and `job.time_in_queue()`
> Fixed issue #464: nice API for job running time and time in queue

- pyquil/api/qvm.py
The docs for `qvm.wavefunction` appear out of date. They say:
```
:return: A tuple whose first element is a Wavefunction object,
and whose second element is the list of classical bits corresponding
to the classical addresses.
```
while
```
pq = Program(H(0), H(1)).measure_all()
print(qvm.wavefunction(pq))
>>> (1+0j)|00>
```
This PR fixes this. @mpharrigan
> Fix return type docstring on QVM wavefunction API

- pyquil/tests/conftest.py
- pyquil/tests/test_api.py
- pyquil/tests/test_device.py
New test fixtures for getting a qvm. I'll update semaphore with an API key. If the connections cannot be made, the test will be skipped.
The only test that uses the new functionality in this PR is the new `test_sync_run` (old version moved to `test_sync_run_mock`). The idea is to get it working and then go through piecewise to add tests against real qvms/compilers as appropriate 
cc #424
> Initial faculties for testing against a real qvm

- pyquil/api/_compiler.py
The primary purpose of this is to support testing the compiler workflow on trivial programs that only contain a gate application (or two) with no measure's, but more generally it also seems more correct to not fail on a valid Quil program.
> This allows to QPU-compile programs without MEASURE's

- pyquil/api/_compiler.py
- pyquil/api/_qpu.py
- pyquil/tests/test_qpu.py
* Make robust to unset readout locations ro_sources[idx] === None
* Allow for non-protoquil sequences with multiple measures on one qubit
> Improve QPU readout result unpacking

- pyquil/api/_config.py
- pyquil/tests/test_api.py
Some users with network setups that do aggressive domain name rewriting have the name "localhost" mangled, but the localhost IP address seems to be safe in these scenarios.
> change default compiler/qvm endpoints

- pyquil/api/_quantum_computer.py
- pyquil/device.py
- pyquil/tests/test_quantum_computer.py
- measure all qubits on a qc (not just the ones used in a program)
- return as a dict instead of a 2d numpy array because of sparsely
indexed qubits
cc @kylegulshen
> Latest attempt at figuring out the best semantics for run_and_measure

- docs/source/advanced_usage.rst
- docs/source/basics.rst
- docs/source/compiler.rst
- docs/source/qvm.rst
- docs/source/start.rst
- pyquil/api/_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
The party line is that you should be using qvm's based on real chips. In the absence of the release of those chips, their connectivities, and noise models we provided `get_qc("9q-generic-qvm")` which may have been a big too *generic* of a name.
Now you can `get_qc("9q-square-qvm")` which gives you a 3x3 square lattice (this is what 9q-generic used to be) (9q-generic is kept for compatibility now but will probably be removed soon since it only ever appeared in a beta release). You can also break free of the shackles of a topology with `get_qc("nq-qvm")` where `n` is an integer, e.g. `get_qc("20q-qvm")`. This replaces `get_qc("qvm")` which would under-the-hood construct a 34-qubit topology which broke `run_and_measure` following #561 
cc @ryankarle @tmittal947 @gecrooks
> Better non-device-backed qvm's

- pyquil/api/_devices.py
when a user's 'url' isn't properly set in their .qcs_config
This can be hit with `get_qc`
> Give a better error message for missing config file

- pyquil/api/_qam.py
- pyquil/api/_qpu.py
- pyquil/api/_qvm.py
- pyquil/tests/test_qpu.py
- pyquil/tests/test_qvm.py
Fixes issue #580 
- If you call QuantumComputer.run with a program that has no measurements, you'll get an empty array (shape=(number of trials, 0))
- Also ran into this issue while testing: if you load a program twice, you will get a descriptive warning rather than an assertion error with no message
> Improve messages for errors running programs

- pyquil/api/_qac.py
@abstractmethod is too aggressive. This change means that implementors
don't need to implement this function at class definition time. It
will still raise an error if someone tries to *use* it and it's not
defined, though.
> AbstractCompiler.get_version_info not as "abstract"

- docs/source/start.rst
Opened to fix issue no. 600, but that issue will remain open until config documentation is moved elsewhere.
> Fix swapped names in readthedocs about qcs_config and forest_config

- docs/source/migration.rst
- examples/forest2-simple-prog.py
- pyquil/api/_qam.py
- pyquil/api/_quantum_computer.py
- pyquil/tests/test_qvm.py
To match the language of `write_memory`.
> Rename the QAM method read_from_memory_region to read_memory

- docs/source/compiler.rst
These are some small improvements to the compiler documentation. A little bit of formatting, and also updating the output in light of the change to the `NAIVE` default. Added some notes and caveats.
> improve compiler documentation

- docs/source/_templates/autosumm.rst
- docs/source/apidocs/.gitignore
- docs/source/apidocs/compilers.rst
- docs/source/apidocs/devices.rst
- docs/source/apidocs/qam.rst
- docs/source/apidocs/quantum_computer.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/modules.rst
- pyquil/api/_qac.py
- pyquil/api/_quantum_computer.py
- requirements.txt
Wrangle sphinx autosummary and sprinkle in some organization and cross-referencing.
This PR contains the building-block `pyquil.api` classes and functions. We should grind through everything currently documented in `modules.rst` and give it some structure.
I encourage reviewers to pull this branch and build the docs. They're pretty snazzy!
> First batch of API docs

- docs/source/migration.rst
- pyquil/api/_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
> Add optional memory_map parameter to QuantumComputer.run

- docs/source/basics.rst
- docs/source/compiler.rst
- docs/source/index.rst
- docs/source/quilc-man.rst
- docs/source/qvm-man.rst
- docs/source/qvm.rst
Still need to actually rewrite QVM page and improve, and later add QPU section, but at least the junk is cleared out.
Added references to man pages. @mpharrigan do we want those anywhere in the TOC?
> Add man pages, cleanup QVM page

- docs/source/advanced_usage.rst
- docs/source/migration.rst
Parametric Programs have been deprecated, this section is about migration for anyone who used it, so it is being moved to migration. Otherwise, this feature is documented in Programs and Gates
> Move "ParametricProgram" section from advanced use

- pyquil/_parser/PyQuilListener.py
- pyquil/tests/test_parser.py
Parsing a DEFCIRCUIT which has no qubit parameters outputs an
extraneous spacing before the colon:
```
>>> from pyquil.parser import parse
>>> from pyquil._parser.PyQuilListener import run_parser
>>> from pyquil.quilbase import RawInstr
>>> print(run_parser("DEFCIRCUIT TEST:\n    MEASURE 0 ro\n"))'
[<RawInstr DEFCIRCUIT TEST :
MEASURE 0 ro[0]>]
```
> Fix parsing DEFCIRCUIT without qubits

- docs/source/qvm.rst
There is a typo when .run() method is called
> QVM docs typo

- pyquil/api/_benchmark.py
- pyquil/api/_qac.py
Adds an option to BenchmarkConnection's RB sequence generator to interleave a fixed Clifford through the sequence.
Depends on https://github.com/rigetticomputing/rpcq/pull/12; do not merge until that is in.
> add an interleaver option when generating an RB sequence

- pyquil/paulis.py
The shift from python 2 to 3 makes some code redundant. This change removes this redundancy in `paulis`.
> Minor code clean up for python 3 version

- pyquil/api/_qam.py
- pyquil/api/_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
I was able to put a `QPU`-backed `QuantumComputer` object into a weird state by `C-c`'ing during a call to `QuantumComputer.run`, so this facility should help.
**Bonus**: Removed unused `_n_shots` and `_n_bits` attributes from the `QAM`
> Add reset method to QuantumComputer and QAM to return to initial state

- pyquil/paulis.py
Removing some redundant (and confusing) code used in calculating the result for a PauliTerm raised to some (integer) power. For one, the identity multiplied by several identities will always just yield an identity. Secondly, we can check for triviality by simply checking for the number of qubits being operated on[*], instead of more convolutedly checking whether the list of identities operating on the available qubits is an empty list or not.
[*] This itself seems like a dubious check, since presumably we are unable to ever create a `PauliTerm` with no qubits, even if we do something like `PauliTerm.from_list([])`. We can nevertheless check for this in a less confusing manner, as in the code change here.
UPDATE:
** (Correcting myself on point [*])
It is indeed possible to produce a …
> Removing redundant code used to calculate powers of PauliTerms

- pyquil/paulis.py
Minor doc-string improvement: The logic for check_commutation really only uses a result from `arXiv:1405.5749v2` (and not also `arXiv:1108.4318`, so this ref is removed). Furthermore, in that paper, the result says that two PauliTerms commute when the number of "coincidences" (i.e. same operator for same qubit) is even if the number of qubits is even, and is odd when the number of qubits is odd -- this is the same as checking that the number of non-coincidences is always even, and this is clarified in the doc-string.
Minor code improvement: We never use the index of the pauli_list, so we simply loop over the terms in this list, instead of its enumerated version.
> Small doc-string/code improvement for check_commutation

- pyquil/paulis.py
- pyquil/tests/test_paulis.py
- pyquil/tests/test_paulis_with_placeholders.py
The functions `is_zero()` and `is_identity()` weren't always checking correctly for their respective checks. Moreover, some of the unit tests were confusing identities for zero operators, e.g. the commutator of commuting operators is the zero, and the not the identity, operator. These issues have been fixed, and a few more unit tests have been added.
> Fix is zero and identity

- docs/source/qvm.rst
Contains clarifying info about QVM, and QPU, as pyQuil objects vs the actual endpoints.
QVM: use from command line, server mode, mention WavefunctionSim
QPU: links to QCS, overview
Quantum Computer: instantiation, run, run_and_measure, making any device topology, simulating qpu w qvm
> Add information about QuantumComputer

- docs/source/start.rst
Used this during a fresh install and figured it may as well be in the docs.
> add rpm dependencies install command for local SDK

- pyquil/api/_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
`get_qc` will return a qpu with the given name or a qvm based off of the named qpu. It also has two "hardcoded" qvms that aren't based on a real device: `9q-square-qvm` and `{n}q-qvm`. Users probably want the ability to give their own topology and/or noise model. This refactors the creation of qvms-not-based-on-a-real-device in anticipation of supporting functionality to have the user create a qvm of their liking.
In particular, `_get_qvm_with_topology` can be made public, documented, and advertised for building a qvm with a custom topology.
> Refactor get_qc helper functions

- pyquil/api/_quantum_computer.py
Issue first encountered when using a Pragma command. 
`validate_protoquil` has more complete logic, and will throw an error if an incorrect instruction is observed.
> remove redundancy in checking the validity of a program

- pyquil/latex/latex_config.py
The preamble was extended with a few options. It does not affect normal compilation with `pdflatex`. If `pdflatex` is run with the `-shell-escape` flag, it will generate a PNG along with the PDF. This makes it easier to read the image of the circuit in a Jupyter notebook.
> Extra parameters for writing a LaTeX to enable generating a PNG image

- pyquil/api/_base_connection.py
In version 1.2.0, quilc changed its URI matching strategy during dispatch from "does the prefix match?" to "is it an exact match?" Internally, the main compilation endpoint is named "/", but pyQuil (confirming to the 1.3 URIs) was sending requests to "/quilc". This won't work anymore.
Looks like `pyquil/api/_benchmark.py` and all of the QVM methods are safe from this.
Another option is to merge the RPCQ-enabled-quilc pyQuil branch ( https://github.com/rigetti/pyquil/pull/730 ), now that an RPCQ-enabled version of quilc is available. Because that branch removes HTTP endpoint support entirely, it dodges this bug, but it also requires some user education, since the startup flags for quilc change from `-S` to `-R`. I don't know what the right move here is.
> reflect quilc URI strictness

- examples/quantum_die.py
The current quantum die program in examples only rolls a die with the number of sides equal to a power of 2. So if for example the user inputs '5' for a 5-sided die, the result can be any integer from 1,...8. This program re-rolls the die if the result is greater than the number of sides.
> quantum die program

- docs/source/advanced_usage.rst
- docs/source/compiler.rst
- docs/source/start.rst
- pyquil/api/__init__.py
- pyquil/api/_benchmark.py
- pyquil/api/_compiler.py
- pyquil/api/_config.py
- pyquil/api/_quantum_computer.py
- pyquil/api/_qvm.py
- pyquil/tests/conftest.py
- pyquil/tests/test_api.py
- pyquil/tests/test_qvm.py
The referenced PR requires the absolute latest quilc, which will be release simultaneously with pyQuil 2.3. For an easier transition we're not going to bump this requirement until pyquil 2.4 at which point the required version of quilc will have been in the wild for ~a month. The new quilc is still backwards compatible with the http interface.
I'll re-merge #730 after the release of pyquil 2.3
> Revert "remove Local variants of QVMCompiler and BenchmarkConnection (#730)"

- pyquil/operator_estimation.py
Hundreds of warnings are printed when running pytest asking for this change
> np.asscalar(a) -> a.item()

- .gitlab-ci.yml
public quilc image: https://hub.docker.com/r/rigetti/quilc
public qvm image: https://hub.docker.com/r/rigetti/qvm
> Use the OSS qvm/quilc Docker images in gitlab CI services instead

- docs/source/compiler.rst
- pyquil/api/_quantum_computer.py
- pyquil/quil.py
- pyquil/tests/test_quil.py
Update docs to say native quil rather than protoquil, update quantum computer to validate that the program being ran is SUPPORTED quil rather than protoquil, update definition of protoquil to be in the spirit of its original intended usage, update tests.
The idea is that Protoquil is a subset of Quil without control flow or classical instructions. Its definition shouldn't change. We were using it to validate whether programs will run on our hardware, which isn't a perfect mapping. Supported Quil is currently more restrictive, but is also a definition that will change over time as we support more operations on hardware. At some point in the future, it should even be less restrictive than ProtoQuil.
Open to ideas/changes if I've gotten anything wrong :)
> Clear up usage of 'protoquil'

- docs/source/advanced_usage.rst
- docs/source/compiler.rst
- docs/source/start.rst
- pyquil/api/_compiler.py
Checks the quilc URL to ensure that it at least looks like a ZMQ address. This will help users migrate their config files, should they have customized that address and forgotten to change it during the upgrade.
> add quilc protocol check

- pyquil/paulis.py
A PauliTerm and tuple of (name, index) are *almost* similar enough for
duck typing to work, but not quite.
Would see a confusing error if doing something like
`PauliTerm.from_list([sZ(0), sX(1)])`
Closes #762.
> TypeError in PauliTerm.from_list

- pyquil/api/_wavefunction_simulator.py
Post-closure comments on #757 pointed out that the memory map argument to `WavefunctionSimulator.run` had a different type signature from `QuantumComputer.run`. This PR modifies the former to match the latter and adds a deprecation warning about this conversion.
> modify WavefunctionSimulator.run's memory_map's type

- pyquil/operator_estimation.py
- pyquil/tests/test_operator_estimation.py
Addresses #825 and (partly) #826 . This fixes a few issues:
- The calibration program should be aware of the readout error model introduced in TomographyExperiment's Program
- The calibration program should be symmetrized as well
- Using `run` instead of `run_and_measure` (see https://github.com/rigetti/pyquil/issues/830)
Additionally, this also makes the calibration program inherit noisy gate definitions from the main TomographyExperiment's program.
Note however that the calibration program is wholly composed of parametric gates, for which we cannot currently define noisy gates (see [#832](https://github.com/rigetti/pyquil/issues/832)), so the calibration won't actually be sensitive to anything but the readout errors for now. Nevertheless, for forward compatibility, we introduce the …
> Fix meas obs

- pyquil/api/_compiler.py
Having a `None` timeout for `QVMCompiler` objects results in indefinite hanging, so we choose a number. It also feels like 10 seconds is a bit excessive, so we set both `QVMCompiler` and `QPUCompiler` objects to be 5 seconds instead.
> Compiler timeout

- pyquil/quil.py
- pyquil/tests/test_quil.py
Rather than a list object. 
Closes #847
> Slice of Program object returns Program object

- requirements.txt
- setup.py
RPCQ had a lower-bound in setup.py but not requirements.txt.
Closes #822.
> Strict version lower-bounds on RPCQ and NetworkX

- pyquil/api/_benchmark.py
The longer description now matches the symbols. I checked that the action really is CPC^dagger
> Fixed comment.

- pyquil/api/_benchmark.py
- pyquil/tests/test_api.py
Returning identity if `pauli_in` input to `apply_clifford_to_pauli` is identity. Previously, that function would throw an error if `pauli_in` was the identity. This assumes the action specified in PR #836.
> Making `apply_clifford_to_pauli` work with identity input

- pyquil/api/_benchmark.py
> Provide a non-None 10 second default timeout to get_benchmarker

- examples/forest2-simple-prog.py
- pyquil/quilatom.py
- pyquil/tests/test_quil.py
- requirements.txt
Closes #599, #667.   
It's not a complete fix since you can still get a `MemoryReference` that has no `declared_size` from the pyQuil parser, but it at least guards against the manually-instantiated case.
> Raise IndexError in MemoryReference.__getitem__()

- pyquil/api/_base_connection.py
- pyquil/api/_benchmark.py
- pyquil/api/_compiler.py
- pyquil/api/_config.py
- pyquil/api/_quantum_computer.py
- pyquil/api/_qvm.py
- pyquil/operator_estimation.py
- pyquil/tests/conftest.py
- pyquil/tests/test_api.py
- pyquil/tests/test_operator_estimation.py
`COMPILER_URL` is being replaced by `QUILC_URL` and `QPU_COMPILER_URL` as they are now separate services within QCS.
> Distinguish between quilc and the QPU compiler endpoints

- docs/source/basics.rst
This PR is a small changes to the docs for the DELAY PRAGMA.
> clarify time arg in delay docs and delay effects

- docs/source/start.rst
The `local_qvm` function is great for beginners (or anyone really) to ensure that the local QVM and Quilc are running without needing to jump into a terminal. Particularly when one is developing in jupyter notebooks and jumping between them it is a good way to make sure the env is set up right. 
This PR surfaces this functionality to the getting started so that developers are aware that this quality of life function exists.
> add local_qvm to getting started docs

- pyquil/operator_estimation.py
- pyquil/tests/test_operator_estimation.py
Resolves Issue #864. Also introduces a few other minor cosmetic changes:
- Changes the name of the optional argument `readout_symmetrize` to `symmetrize_readout` in `measure_observables(..)`, to make it read more similar to the optional argument `calibrate_readout`
- Updates the warning message in `_exhaustive_symmetrization` to use f-strings instead of the old way of using `format`
> Replace standard deviation in operator estimation with standard error

- .gitlab-ci.yml
- README.md
- docs/source/changes.rst
- pyquil/__init__.py
- pyquil/operator_estimation.py
- pyquil/tests/test_operator_estimation.py
#870 and #896 are the main offenders. This PR also cuts down the running time of the operator estimation unit tests by about a factor of 3, so that they dont add 16 minutes to the build. However, there is chance they could fail now due to undersampling (I did my best to test, but it remains to be seen if my testing was thorough enough). In parallel, I have enabled the qvm- and quilc-related tests in Semaphore (the operator estimation tests fall in this bucket). I need to address #898 before they will start working in GitLab CI.
> Bump version to 2.7.1 for a patch release

- docs/source/changes.rst
- pyquil/__init__.py
- pyquil/operator_estimation.py
- pyquil/tests/test_operator_estimation.py
The `readout_symmetrize` change in #870 snuck past the 2.7.1 patch (#899).
>  Bump version to 2.7.2 for a patch release

- pyquil/operator_estimation.py
`symmetrize_readout` and `calibrate_readout` are both optional arguments to `measure_observables` that can be `None` and have a very specific meaning when they do so. This change makes it clear that those inputs can be `type(None)` (previously, in python 2.x, `NoneType`) in principle.
> Use Optional typing for some measure_observables params

- requirements.txt
- setup.py
A backwards incompatible change was made to RPCQ for this
release. pyQuil >=2.7.0 will not work with RPCQ <2.5.0
Please add reviewers if they may need to know about this.
> Raise RPCQ requirement to 2.5.1

- .gitlab-ci.yml
- pyquil/api/_compiler.py
- pyquil/api/_qvm.py
- pyquil/tests/conftest.py
- pyquil/tests/test_api.py
- pyquil/tests/test_qpu.py
From the discussions with @notmgsk in #891. This should be merged right before the 2.8.0 release.
The new `DefPermutationGate` class defined in #891 only works with the new classical logic features in quilc/qvm 1.8.0, and therefore this aims to prevent any version mismatch snafus.
Fixes #898.
> Check that QVM/quilc servers are running and compatible

- pyquil/gates.py
- pyquil/quil.py
- pyquil/tests/test_quil.py
This PR adds support for QubitPlaceholders (and Qubits in general) to the RESET instruction, which used to exclusively take a qubit index. Since QubitPlaceholders don't have indices during program construction, the RESET function wouldn't work with them.
This could be worked around by calling ResetQubit() to explicitly create a RESET instruction with the QubitPlaceholder as the target, but address_qubits() ignored ResetQubit instructions so they wouldn't be mapped to the assigned qubit indices. This PR fixes that too.
> Add QubitPlaceholder support to RESET, add ResetQubit support to address_qubits()

- pyquil/quil.py
- pyquil/tests/test_quil.py
Hi all,
We ran into a problem where taking the adjoint of a controlled gate using the dagger() function would drop the CONTROLLED modifiers on the new inverted gate. This was a similar problem to #905, and based on the fix in #907, we figured out what needed to be changed in order to preserve the modifiers. This PR is a simple fix to the dagger() function that does exactly that.
We tested it on our implementation of Shor's algorithm and can confirm that it works there, but please review it and let me know if you see it breaking anything we didn't manage to test.
> Fix missing modifiers in dagger()

- pyquil/quil.py
- pyquil/tests/test_quil.py
This removes a bunch of logic around creating inverse gates from
user-defined gates. If anyone thinks that stuff is useful, then I
would argue that it should be in some util function, not in
Program.dagger().
Kept kw args for backwards compat :(
> Use native Gate.dagger() in Program.dagger()

- docs/source/advanced_usage.rst
- docs/source/compiler.rst
- docs/source/conf.py
- docs/source/intro.rst
- docs/source/noise.rst
- docs/source/qvm.rst
- examples/ReadoutNoise.ipynb
Description
-----------
Fixes for small typos and the like that I encountered while reading over the docs.
Here is a screenshot of http://docs.rigetti.com/en/stable/intro.html showing broken inlinemath rendering.
https://drive.google.com/open?id=1xQSYo5aXZtFcfhxVsq2ZbzahTTL_sQ5d
I am not sure why this is broken, since the MathJax config includes `"inlineMath": [["$", "$"], ["\\(", "\\)"]]`. I think maybe the `\\(`s in the rst source file need an extra escape. In any case, `intro.rst` was the only file still using latex-style `\\(..\\)` delimiters, so I just switched everything over to `:math:` style. Screenshot of same section after these changes:
https://drive.google.com/open?id=1rUdnlmmR24Fq4qJ48zVygehqvCrFqaM0
> Fix inlinemath rendering in intro.rst + other small doc typos

- docs/Makefile
- docs/source/apidocs/wavefunction.rst
- docs/source/basics.rst
- docs/source/compiler.rst
- docs/source/conf.py
- docs/source/migration.ipynb
- docs/source/migration2-qc.ipynb
- docs/source/migration4.rst
- docs/source/qvm.rst
- docs/source/start.rst
- docs/source/wavefunction_simulator.rst
- pyquil/gates.py
- pyquil/noise.py
- pyquil/operator_estimation.py
- pyquil/quil.py
- pyquil/wavefunction.py
Description
-----------
Fix a bunch of warnings when building the sphinx docs. See individual commit messages for the full list of warnings addressed by this PR.
EDIT: #927 is now merged.
~~Note on merge dependencies:~~
~~After these changes, only one warning remains, which will be fixed when/if #927 is merged. Because this PR includes a tentative change to make sphnix-build treat warnings as errors, this PR should only be merged after #927 (unless we drop the warnings-as-errors change from this PR).~~
Fixes #583
Checklist
---------
> Fix sphinx warnings

- docs/source/changes.rst
- pyquil/tests/test_unitary_tools.py
- pyquil/unitary_tools.py
Description
-----------
In `unitary_tools.py` we provide functionality for converting a pyquil `Gate` into a matrix. Gates which had been modified with a `dagger()` call were not being converted properly to the daggered matrix. 
closes #932
Checklist
---------
> Support for dagger when converting gate to matrix.

- docs/source/changes.rst
- docs/source/compiler.rst
- docs/source/start.rst
- pyquil/api/_compiler.py
- pyquil/api/_qac.py
- pyquil/api/_quantum_computer.py
- pyquil/tests/utils.py
This makes, in a backwards-compatible fashion:
* Adds `protoquil` keyword argument to `QuantumComputer.compile()`. When this is set to `True` the compiler will employ it's protoquil restrictions on input/output.
Prior to this PR the compiler was configured at launch-time to produce protoquil (via the `-P` option). This could not be changed while the server was running. That option remains in the compiler, but now there is the above endpoint that enables the protoquil option as-and-when
the user desires it.
This shouldn't be merged before https://github.com/rigetti/quilc/pull/289.
TODO:
> Opt-in to protoquil from compiler

- docs/source/changes.rst
- pyquil/quil.py
- pyquil/tests/test_quil.py
Description
-----------
Closes #970
Also threw in the fix that closes #634 
Checklist
---------
> Add merge_programs support for DefPermutationGate

- .github/PULL_REQUEST_TEMPLATE.md
- .gitlab-ci.yml
- CHANGELOG.md
- docs/source/changes.rst
Need to use `pandoc` to convert to `changes.rst` during the docs creation process.
> Add markdown version of the changelog

- CHANGELOG.md
- docs/source/changes.rst
- pyquil/tests/test_operator_estimation.py
- requirements.txt
- tox.ini
Description
-----------
We have a number of tests that have a small but non-zero chance of failing. This commit makes pytest retry any test that fails (and retry only a single time). Reduces the likelihood that a stray numerical instability causes the whole test run to fail.
Checklist
---------
> Rerun flaky unit tests once more when they fail

- CHANGELOG.md
- pyquil/pyqvm.py
- pyquil/tests/test_quantum_computer.py
This PR removes the requirements enforced in PyQVM that let it _always_ do efficient `run_and_measure`-style sampling of bitstrings.
On reflection, it might be desirable to offer a separate pathway that does do `run_and_measure`-style sampling, rather than remove it outright. I'll return to this before making this a real PR.
> Remove requirements used for RAM-style sampling

- CHANGELOG.md
- pyquil/api/_qpu.py
Description
-----------
This is a bandaid to close #981.  #873 modified `QVM` and `QPU` to remove the restriction that declared memory regions be named "ro". The `QVM` change works nicely, but upon testing on the QPU an error was found. There was a type error (ndarray vs list), but more importantly there was a logical error in using `ro_sources` where `len(bitstrings)` ought to have been used.
Note this is only a bandaid because memory regions on the QPU are still not populated in `_memory_results`. I will open an issue to fix that separately, in the interest of unblocking a release.
Checklist
---------
> Undo erroneous logic filling out non-“ro” memory on QPU

- CHANGELOG.md
- docs/source/apidocs/quantum_computer.rst
- docs/source/start.rst
- pyquil/api/__init__.py
- pyquil/api/_quantum_computer.py
- pyquil/tests/conftest.py
- pyquil/tests/test_quantum_computer.py
Description
-----------
I renamed `local_qvm` to `local_runtime`, hinting that it does not just start a qvm but also takes care of quilc.
Additionally I added optional parameters that can be provided to that function, giving the user more control over the running processes. 
use_protoQuil defaults to `False`, is that a sensible default?
Currently also exposes options to define custom ports for quilc and qvm, but tbh I'm not sure if that makes sense since (at least right now) I don't see that any other than default ports would work. What do you think?
I also enabled documentation to be generated by this method in sphinx.
Let me know your thoughts on all these and if there are any other options that should get exposed!
Resolves #972 
Checklist
---------
[auto-close …
> Renamed local_qvm, added options to start quilc and qvm

- .gitlab-ci.yml
- CHANGELOG.md
Description
-----------
The docs (and the tox.ini) say that we support Python 3.7, but we don't actually run the tests using that version of Python as part of the CI. Now we do!
Checklist
---------
> Run the GitLab CI test suite on Python 3.7 as well

- CHANGELOG.md
- pyquil/api/_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
Description
-----------
There was an accidental truncation of strength two arrays that yielded at least some of them invalid. I removed the truncation during creation of the array altogether, to match behavior of strength 3. Now, arrays are constructed for more than desired qubits if necessary, and automatically truncated to desired number of qubits in `_symmetrization`.
Checklist
---------
> Fix strength 2 orthogonal array construction

- CHANGELOG.md
- pyquil/latex/latex_generation.py
Description
-----------
Allow non-gate instructions in `to_latex()`. Closes #637.
Checklist
---------
> Allow non-gate instructions in to_latex()

- CHANGELOG.md
- pyquil/api/_qvm.py
- pyquil/operator_estimation.py
- pyquil/tests/test_api.py
- pyquil/tests/test_magic.py
- pyquil/tests/test_numpy_simulator.py
- pyquil/tests/test_operator_estimation.py
- pyquil/tests/test_quantum_computer.py
- pyquil/tests/test_quil.py
- pyquil/tests/test_reference_wavefunction_simulator.py
- pyquil/tests/test_unitary_tools.py
Description
-----------
This reduces from pytest warnings from 1365 to 63, and partially resolves #997. There is no substantial change in behavior of any code. Mostly this is just a matter of various features being deprecated without updating the tests which use them. I might fix the other 63 next week, but I am running out of spare time today.
Checklist
---------
> Reduce deprecated feature warnings in tests

- CHANGELOG.md
- CONTRIBUTING.md
- pyquil/tests/conftest.py
- pyquil/tests/test_operator_estimation.py
- pyquil/tests/test_quantum_computer.py
- pyquil/tests/test_reference_density_simulator.py
- tox.ini
Description
-----------
A few tests dominate the runtime of the test suite, and this makes me less likely to run tests. On my system,
```
== slowest 10 test durations ==
45.54s call     pyquil/tests/test_quantum_computer.py::test_run_symmetrized_readout_error
40.33s call     pyquil/tests/test_reference_density_simulator.py::test_for_negative_probabilities
15.67s call     pyquil/tests/test_operator_estimation.py::test_measure_observables_many_progs
6.24s call     pyquil/tests/test_quantum_computer.py::test_run_pyqvm_noisy
4.40s call     pyquil/tests/test_operator_estimation.py::test_measure_observables_symmetrize_calibrate
4.34s call     pyquil/tests/test_operator_estimation.py::test_2q_unitary_channel_fidelity_readout_error
2.97s call …
```
> Mark and skip particularly slow unit tests

- CHANGELOG.md
- pyquil/paulis.py
- pyquil/tests/test_api.py
- pyquil/tests/test_device.py
- pyquil/tests/test_parser.py
- pyquil/tests/test_paulis.py
- pyquil/tests/test_paulis_with_placeholders.py
- pyquil/tests/test_quantum_computer.py
- pyquil/tests/test_quil.py
- pyquil/tests/test_qvm.py
Description
-----------
This addresses the bulk of the warnings from the test suite, and resolves #997. There are 12 remaining warnings; these should be addressed separately (e.g. in #1004, #1003, https://github.com/rigetti/pyquil/issues/837#issuecomment-532857053).
Checklist
---------
> Clean up bulk of remaining test suite warnings

- CHANGELOG.md
- pyquil/gates.py
- pyquil/quilbase.py
- pyquil/tests/test_parser.py
- pyquil/tests/test_quil.py
Description
-----------
This PR includes changes to bring the pyquil `STORE` and classical comparison instructions in line with the Quil spec. Specifically:
- Allow immediate floats as third arg in prepare_ternary_operands
- Allow immediate values as source arg for STORE and ClassicalStore
- Allow CONVERT to take any valid memory reference designator, i.e. a
MemoryReference, a string, or a tuple of (str, int).
Fixes #815
Checklist
---------
> Fix operand types for STORE and comparison instructions

- CHANGELOG.md
- pyquil/tests/test_unitary_tools.py
- pyquil/unitary_tools.py
Description
-----------
Insert your PR description here. Thanks for contributing to pyQuil! 🙂
Checklist
---------
> Prevent non-constant params in lifted_gate

- CHANGELOG.md
- examples/meyer_penny_game.py
Fixes #1044
Description
-----------
A docstring comment in `meyer_penny_game.py` was referencing a non-existent `examples.rst` file. It appears the referenced content can now be found in `exercises.rst`.
Checklist
---------
> Correct path to exercises.rst in meyer_penny_game.py

- .dockerignore
- .gitlab-ci.yml
- CHANGELOG.md
- Dockerfile
Description
-----------
Fixes #1037.
The image is now much smaller:
- 935.72 MB -> 521.6 MB on DockerHub
- 2.31 GB -> 1.38GB on disk
And the build is much faster (5 mins to 2 mins).
Checklist
---------
> Make the Docker image smaller and build faster

- CHANGELOG.md
- README.md
Description
-----------
This PR updates the Rigetti-Forest Slack invitation link with one that has not expired. This fixes pyQuil issue #1040. 
Checklist
---------
> Update Rigetti Forest Slack Workspace invitation link

- CHANGELOG.md
- docs/source/compiler.rst
- pyquil/api/_qac.py
- pyquil/api/_quantum_computer.py
- pyquil/tests/utils.py
Description
-----------
Slipped through my review of #940 (see https://github.com/rigetti/pyquil/pull/940#discussion_r305418586).
Checklist
---------
> Deprecate positional usage of protoquil compilation arg

- CHANGELOG.md
- pyquil/quilatom.py
- pyquil/tests/test_quil.py
Description
-----------
See #993 for details. This is a much simpler fix than I previously suggested.
Checklist
---------
- [🤷‍♂] Parameters have type hints with [PEP 484 syntax](https://www.python.org/dev/peps/pep-0484/).
- [🤷‍♂] Functions and classes have useful sphinx-style docstrings.
- [🤷‍♂] (New Feature) The docs have been updated accordingly.
- [🤷‍♂] (Bugfix) The associated issue is referenced above using
> Test for presence of π in _expression_to_string

- CHANGELOG.md
- pyquil/paulis.py
Description
-----------
Just uses the `__str__` magic method. Not sure if there is a reason for us to support both the `__str__` and the `compact_str` of a `PauliTerm`  -- maybe they should be merged?
```python
In [1]: from pyquil.paulis import sX
In [2]: sX(1)
Out[2]: (1+0j)*X1
In [3]: sX(1) * sX(2) + sX(1) * sX(2)
Out[3]: (2+0j)*X1*X2
```
Checklist
---------
> Add __repr__ magic methods for PauliSum and PauliTerm

- CHANGELOG.md
- pyquil/_parser/PyQuilListener.py
- pyquil/api/_base_connection.py
- pyquil/api/_quantum_computer.py
- pyquil/api/_qvm.py
- pyquil/gates.py
- pyquil/operator_estimation.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- pyquil/tests/test_gates.py
- pyquil/tests/test_reference_wavefunction_simulator.py
Description
-----------
This PR adds type annotations for the `pyquil.gates`, `pyquil.quilatom`, and `pyquil.quilbase` modules.
~This is still a WIP, but is ready for review. Since I'm new-ish to pyQuil, I probably got the types wrong in several places. See the `TODO`s in the diff for places I'm particularly unsure about. Any hints from reviewers on these are greatly appreciated.~
So far, these pass muster when running `mypy` like so:
```
mypy --ignore-missing-imports --follow-imports=silent pyquil/quilatom.py
mypy --ignore-missing-imports --follow-imports=silent pyquil/quilbase.py
mypy --ignore-missing-imports --follow-imports=silent pyquil/gates.py
```
Resolves #988
TODO:
Checklist
--------- …
> Type annotations for gates, quilatom, and quilbase modules

- CHANGELOG.md
- pyquil/experiment/__init__.py
- pyquil/experiment/tests/test_experiment.py
- pyquil/operator_estimation.py
- pyquil/tests/test_operator_estimation.py
Description
-----------
Rather than having a proliferation of keyword args in `measure_observables`, we can use the `TomographyExperiment` to capture everything we want to do. There's some really ugly deprecation code, but I did what I had to do to make it completely backwards compatible. This change enables future work on parametric-compilation-enabled observable estimation.
Printing out a `TomographyExperiment` now gives you something like this:
```yaml
shots: 1000
active reset: enabled
symmetrization: -1 (exhaustive)
program:
H 1
CNOT 2 1
DAGGER T 1
CNOT 0 1
T 1
... 12 instrs not shown ...
T 0
S 2
MEASURE 0
MEASURE 1
MEASURE 2
settings:
0: Z0_0 * Z0_1→(1+0j)*X0X1
1: Z0_0 * Z0_1→(1+0j)*X0X1
2: Z0_0 * Z0_1→(1+0j)*X0X1
3: Z0_0 * Z0_1→(1+0j)*X0X1
4: Z0_0 * Z0_1→(1+0j)*X0X1
5: Z0_0 * …
```
> Use TomographyExperiment for measure_observables args

- CHANGELOG.md
- pyquil/api/_base_connection.py
Since removing HTTP from `quilc`, the `ForestConnection._quilc_get_version_info()` function has been broken. Thankfully nothing uses it.
> Remove unused code for talking to quilc over HTTP

- CHANGELOG.md
- pyquil/paulis.py
Description
-----------
Only PauliTerm is annotated to keep this PR small.
Checklist
---------
> Add type annotations to the PauliTerm class

- .gitlab-ci.yml
- CHANGELOG.md
- Makefile
- mypy.ini
- requirements.txt
- tox.ini
Description
-----------
Add "make typecheck" target and run it during gitlab CI.
- Add mypy to requirements.txt
- Add mypy.ini
- Add testenv:mypy to tox.ini
- Add a make typecheck target
- Add a typecheck section to .gitlab-ci.yml
Closes #1006
Checklist
---------
> Add "make typecheck" target and run it during gitlab CI

- CHANGELOG.md
- pyquil/latex/_diagram.py
- pyquil/latex/tests/test_latex.py
Description
-----------
This fixes a bug in printing of controlled unitaries. The control line is specified with a placement and offset. The previous version computed the offset incorrectly. I added a test to check this. This bug did not affect gates such as `CNOT`, which were handled by a separate code path.
Checklist
---------
> Fix control line offset in LaTeX for controlled gates

- Dockerfile
Description
-----------
Self explanatory.
Checklist
---------
> Bump QVM docker image version to v1.13.1 for XY

- CHANGELOG.md
- docs/source/qvm.rst
Description
-----------
Correctly declare the size of the ro register in qc.run example.
Fixes #1097
Checklist
---------
> Correctly declare the size of the ro register in qc.run example

- CHANGELOG.md
- pyquil/experiment/_main.py
- setup.py
Description
-----------
If you don't explicitly specify the encoding you want when opening a file, [Python defaults to the platform-dependent LC_CTYPE](https://docs.python.org/3.6/library/functions.html#open). On platforms where this is set to an ascii or "C" locale, this prevents installing pyquil, since `setup.py` tries to read `README.md` and chokes on the `U+1F642 SLIGHTLY SMILING FACE`.
Likewise `test_experiment_deser` fails in `pyquil.experiment.to_json` when it encounters a `U+2192 RIGHTWARDS ARROW` in the str representation of an `ExperimentSetting`.
I noticed this while attempting to install pyquil on CentOS 7, which apparently defaults to an ascii locale.
To reproduce and/or verify the fix, you can 
```
cd /path/to/pyquil
export LC_ALL=C
pip install -e .
pytest …
```
> Specify file encoding to guard against ascii locales

- CHANGELOG.md
- pyquil/paulis.py
Description
-----------
Continuation of the effort to type-annotate paulis.py
Checklist
---------
> Add type annotations to the PauliSum class

- requirements.txt
Description
-----------
Seems that the upgrade from mypy 0.740 to 0.750 broke `make typecheck`. Pinning to 0.740 solves the issue.
Following suggestion of @appleby 
Checklist
---------
> pin mypy to 0.740

- CHANGELOG.md
- pyquil/latex/_diagram.py
- pyquil/latex/tests/test_latex.py
Description
-----------
As it currently stands, programs with RESET operations are not semantically different (in an ideal world) to those without them. Actual drawing of the detailed operation of RESET (which involves a measurement and some small amount of feedback control) is a significant scope creep to this latex code. Thus I propose simply ignoring RESET instructions for the purpose of rendering circuits.
> Allow RESET instructions to silently fall through the latex generation process

- CHANGELOG.md
- Makefile
- docs/source/conf.py
- examples/1.3_vqe_demo.py
- examples/quantum_die.py
Description
-----------
Broadened the scope of flake8 compliance to the entire repo (including examples, docs, etc.)
Checklist
---------
> Run flake8 on the docs and examples directories as well

- CHANGELOG.md
- pyquil/api/_compiler.py
- pyquil/api/tests/test_compiler.py
Description
-----------
Continues the discussion from https://github.com/kalzoo/pyquil/pull/1.
This small change allows compilation to take place over http(s) as well as zeromq, enabling architectural changes within the Rigetti QPU Compiler service.
This should be merged into master once `feature/qpu-authorization` is merged.
Checklist
---------
> Add support for QPU compilation over http(s)

- CHANGELOG.md
- Dockerfile
Description
-----------
Title is self-explanatory.
Checklist
---------
> Bump quilc / qvm parent Docker images to v1.15.1

- CHANGELOG.md
- pyquil/api/_config.py
- pyquil/api/_qpu.py
- pyquil/api/tests/test_config.py
- pyquil/tests/test_qpu.py
Description
-----------
This PR fixes an issue arising on the QMI when a `.forest_config` file is also present and includes `qpu_endpoint_address` and `qpu_compiler_address`. In that case, PyQuil still requested engagement and obtained a keypair, but then attempted to connect to the unencrypted endpoint specified in the `.forest_config`, which hangs.
Checklist
---------
> Only request engagement from dispatch when necessary

- CHANGELOG.md
- pyquil/api/_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
When sending quilc and qvm stdout and stderr to a `subprocess.PIPE`, it's possible for the pipe buffer to fill up and cause the processes to hang when attempting to log on stderr. Switch these to `subprocess.DEVNULL` instead. This means you can no longer read log messages from the handles, but has the advantage that it doesn't require user intervention to periodically drain the pipe buffer to prevent a hang.
Note that this is a backwards-incompatible change.
Closes #1110
Checklist
---------
> Send local_forest_runtime stdout and stderr to DEVNULL

- CHANGELOG.md
- pyquil/quil.py
Description
-----------
This is about 50% of the quil.py file annotation. I'm not doing the entirety of the methods so that the diff is not too huge, and also there are several annotations that I am unsure of even after consulting the annotation of quilbase.py
Checklist
---------
> Partially add type annotations to the Program class

- CHANGELOG.md
- Makefile
- docs/source/apidocs/noise.rst
- pyquil/noise.py
- pyquil/quil.py
Description
-----------
Remaining mypy errors of noise.py:
```
pyquil/noise.py:477: error: Argument 2 to "get_noisy_gate" has incompatible type "List[Union[Expression, Any, complex]]"; expected "Tuple[float, ...]"
pyquil/noise.py:558: error: Call to untyped function "define_noisy_gate" in typed context
pyquil/noise.py:562: error: Call to untyped function "define_noisy_readout" in typed context
pyquil/noise.py:580: error: Argument 1 to "tuple" has incompatible type "List[Union[Expression, Any, complex]]"; expected "Iterable[float]"
pyquil/noise.py:766: error: Argument 2 to "_apply_local_transforms" has incompatible type "Generator[Any, None, None]"; expected "Sequence[Any]"pyquil/noise.py:784: error: Argument 2 to "_apply_local_transforms" has incompatible type "Generator[Any, None, …
```
> Add type annotations to noise.py and verify in the CI

- CHANGELOG.md
- pyquil/gates.py
- pyquil/quilbase.py
Description
-----------
Fix two odd bits of string concatenation, one of which was likely a side effect of running black. Both found via this flake8 plugin (which I have used and contributed to):
https://github.com/keisheiled/flake8-implicit-str-concat
Checklist
---------
> Fix string concatenation style

- CHANGELOG.md
- docs/source/migration2-qc.ipynb
- pyquil/api/_quantum_computer.py
Description
-----------
**Eschew FutureWarning by passing np.vstack a sequence**
Fixes #1095
**Add protoquil kwarg to MyLazyCompiler.quil_to_native_quil**
Otherwise you get the following error when executing the last cell in this notebook:
TypeError: quil_to_native_quil() got an unexpected keyword argument 'protoquil'
Checklist
---------
> Fixes for migration2-qc.ipynb

- CHANGELOG.md
- pyquil/quil.py
Description
-----------
All of the classes that are derived from `AbstractInstruction` doesn't have `allow_placeholders` argument in their `out()` method.
Checklist
---------
> Remove unused method Program._out() in quil.py

- CHANGELOG.md
- pyquil/api/_base_connection.py
- pyquil/api/_config.py
- pyquil/api/_devices.py
- pyquil/api/_qpu.py
- pyquil/api/_quantum_computer.py
- pyquil/experiment/_main.py
- pyquil/experiment/_program.py
- pyquil/magic.py
- pyquil/noise.py
- pyquil/numpy_simulator.py
- pyquil/pyqvm.py
- pyquil/reference_simulator.py
Description
-----------
Work in progress for #1140, fixing RST violations reported by docutils via flake8-rst-docstrings
Checklist
---------
> Ensure valid RST in docstrings

- CHANGELOG.md
- Makefile
- pyquil/noise.py
- pyquil/quil.py
Description
-----------
Continuation of the effort to annotate quil.py.
Checklist
---------
> Finish the rest of the type annotations for quil.py

- CHANGELOG.md
- Makefile
- mypy.ini
- pyquil/latex/_diagram.py
- pyquil/latex/_ipython.py
- pyquil/latex/_main.py
- pyquil/latex/latex_generation.py
Description
-----------
More fun with typing.
Checklist
---------
> Add typing to the latex module and mypy check in CI

- .github/PULL_REQUEST_TEMPLATE.md
- .gitlab-ci.yml
- .travis.yml
- CHANGELOG.md
- pyquil/latex/_diagram.py
Description
-----------
Turns out `mypy` cannot typecheck the py36-vendored dataclasses because support was only added in py37. Thus, we need to upgrade the CI to use py37 in order to avoid ignoring large swaths of code during the type-checking process. Problem is, Semaphore Classic doesn't natively support py37, so I've decided to give Travis a try as a replacement. The build matrix stuff is pretty slick, and using Travis allows for the fork PR builds to be source-controlled in the form of a `.travis.yml` file (rather than in the Sempahore Classic UI).
TODO
------
Checklist
---------
> Start using Travis CI, upgrade style checks to py37

- .gitlab-ci.yml
- CHANGELOG.md
- Makefile
- pyquil/experiment/_group.py
- pyquil/experiment/_main.py
- pyquil/experiment/_program.py
- pyquil/experiment/_result.py
- pyquil/experiment/_setting.py
- pyquil/latex/_ipython.py
Description
-----------
Keep the train going.
Checklist
---------
> Add typing to experiment module and verify in CI

- CHANGELOG.md
- Makefile
- pyquil/device/_isa.py
- pyquil/device/_main.py
- pyquil/device/_specs.py
- pyquil/device/tests/test_device.py
- pyquil/tests/test_quantum_computer.py
Description
-----------
Fixes #980 
Checklist
---------
> Use dataclasses instead of namedtuples in device module

- CHANGELOG.md
- pyquil/experiment/_group.py
- pyquil/experiment/_main.py
- pyquil/experiment/_memory.py
- pyquil/experiment/_setting.py
- pyquil/paulis.py
- pyquil/simulation/_numpy.py
- pyquil/simulation/_reference.py
Description
-----------
This currently reduces the mypy error from 31 down to 20. For the rest, I am not so sure how to handle them.
Checklist
---------
> Reduce mypy errors in paulis.py

- CHANGELOG.md
- pyquil/device/_isa.py
- pyquil/device/_main.py
- pyquil/device/tests/test_device.py
Description
-----------
Updates simulated `NxDevice`s to support `XY` gates as well as `CZ` gates, which better reflects actual Rigetti devices.
*Warning:* I nubbed out some tests because to/from_dict can't really be expected to be inverse / idempotent operations.
Checklist
---------
[travis]: …
> NxDevices support CZ and XY by default

- CHANGELOG.md
- docs/source/apidocs/experiment.rst
- docs/source/apidocs/quantum_computer.rst
- pyquil/api/_quantum_computer.py
- pyquil/api/tests/test_quantum_computer.py
- pyquil/experiment/__init__.py
- pyquil/experiment/_calibration.py
- pyquil/experiment/_main.py
- pyquil/experiment/_result.py
- pyquil/experiment/_setting.py
- pyquil/experiment/tests/test_main.py
- pyquil/experiment/tests/test_result.py
- pyquil/noise.py
- pyquil/operator_estimation.py
- pyquil/tests/test_operator_estimation.py
Description
-----------
Following up on #1100, this PR adds top-level support for readout calibration and correction, making it easy to succinctly run readout-error-mitigated algorithms on modest numbers of qubits (see fig).
```python
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np
from pyquil import Program
from pyquil.api import get_qc
from pyquil.experiment import (
ExperimentSetting, TomographyExperiment, correct_experiment_result
)
from pyquil.gates import CNOT, H, RESET, RZ
from pyquil.noise import NoiseModel
from pyquil.paulis import sZ
def asymmetric_ro_model(
qubits: list, p00: float = 0.95, p11: float = 0.90
) -> NoiseModel:
aprobs = np.array([[p00, 1 - p00], [1 - p11, p11]])
aprobs = {q: aprobs for q in qubits}
return NoiseModel([], aprobs)
noise_model …
```
> QuantumComputer method to perform readout calibration

- CHANGELOG.md
- pyquil/api/_qam.py
- pyquil/api/_quantum_computer.py
Description
-----------
Modified write_memory() for accepting lists in addition to values + offsets when writing to classical memory registers. Closes #658.
Checklist
---------
> Support instead providing a list of values to write_memory()

- CHANGELOG.md
- Makefile
- mypy.ini
- pyquil/operator_estimation.py
- pyquil/parser.py
- pyquil/paulis.py
- pyquil/pyqvm.py
- pyquil/tests/test_wavefunction.py
- pyquil/wavefunction.py
Description
-----------
Some typing odds and ends.
Next PR will be to deal with the API module, which is the only thing left.
Checklist
---------
> Add type hints to all remaining top-level files

- CHANGELOG.md
- docs/source/apidocs/experiment.rst
- pyquil/api/_qam.py
- pyquil/api/_quantum_computer.py
- pyquil/api/tests/test_quantum_computer.py
- pyquil/experiment/__init__.py
- pyquil/experiment/_group.py
- pyquil/experiment/_main.py
- pyquil/experiment/_setting.py
- pyquil/experiment/tests/test_group.py
- pyquil/experiment/tests/test_main.py
- pyquil/operator_estimation.py
- pyquil/simulation/tests/test_reference_density.py
- pyquil/tests/test_operator_estimation.py
Description
-----------
I prefer the shorter name, and these hybrid/tomography-like experiments are the focus of our quantum cloud platform.
Checklist
---------
> Rename TomographyExperiment to Experiment

- CHANGELOG.md
- pyquil/tests/test_qpu.py
Description
-----------
`QPUCompiler` no longer accepts an `endpoint` init arg. Replace it with `quilc_endpoint` and `qpu_compiler_endpoint`.
This got the QPU tests working against a fake fridge on my local machine.
Checklist
---------
> Fix QPUCompiler init args in test_qpu.py

- CHANGELOG.md
- pyquil/experiment/_group.py
- pyquil/experiment/_main.py
Description
-----------
This fixes two small bugs, in which `Experiment` objects lost meaningful metadata. Specifically:
- `num_shots` was not being preserved when `RESET` instructions were stripped
- `symmetrization` was not preserved when grouping instructions
This fixes both of these issues.
Checklist
---------
[sphinx]: …
> Actually track metadata in experiment manipulations

- .gitlab-ci.yml
- CHANGELOG.md
- CONTRIBUTING.md
Description
-----------
Previously, the `include`-d pipelines in the GitLab CI YAML were in private repositories, and difficult to reason about. This PR takes advantage of the now-public [gitlab-pipelines](https://github.com/rigetti/gitlab-pipelines) repository's template YAMLs, and adds a section to the contributing guide about
managing the CI/CD pipelines.
Checklist
--------- …
> Use the job template YAMLs from rigetti/gitlab-pipelines

- CHANGELOG.md
- README.md
Description
-----------
This pull request fixes #1169 by adding a named, updated QCS signup link. 
Checklist
---------
> Fix #1169; Add updated named link for QCS access

- CHANGELOG.md
- docs/source/index.rst
- docs/source/start.rst
Description
-----------
This pull request fixes #1172 by updating the SDK download link and instructions. 
It also updates a broken link for the Rigetti-Forest Slack workspace and a broken link for QCS access requests, and it provides installation instructions for Windows. 
Checklist
---------
[travis]: …
> Update SDK link and download instructions

- CHANGELOG.md
- pyquil/quil.py
- pyquil/tests/test_quil.py
Description
-----------
PyQuil considers `HALT` to be a valid protoquil function. Neither the compiler nor the `native_quil_to_executable` handler agree with this, e.g.
```
erik-macbook:magicl erik$ echo "H 0" | quilc 2>/dev/null
RZ(pi/2) 0                              # Entering rewiring: #(0 1 2 3 4 5 6 7)
RX(pi/2) 0
RZ(pi/2) 0
HALT                                    # Exiting rewiring: #(0 1 2 3 4 5 6 7)
erik-macbook:magicl erik$ echo "H 0" | quilc -P 2>/dev/null
RZ(pi/2) 0                              # Entering rewiring: #(0 1 2 3 4 5 6 7)
RX(pi/2) 0
RZ(pi/2) 0                              # Exiting rewiring: #(0 1 2 3 4 5 6 7)
```
This PR just removes `HALT` from the list of accepted protoquil instructions.
Checklist
---------
[auto-close]: …
> Remove HALT from valid protoquil instructions

- CHANGELOG.md
- docs/source/noise.rst
Fixes #1174
Description
-----------
In the docs, code was copied and edited for a new example. The corresponding comment in the code was copied, but not edited. This PR fixes the comment.
Checklist
---------
- [ x] The above description motivates these changes.
- [ x] (Bugfix) The associated issue is referenced above using [auto-close keywords][auto-close].
> Fix comment not edited for code change

- CHANGELOG.md
- CONTRIBUTING.md
Description
-----------
Add some documentation about publishing packages to conda-forge and to rigetti's own conda channel.
This is somewhat specific to rigetti's release process, so I can see why it wasn't included here in the first place, but at the same time these are public-facing conda packages related to the pyquil release process, so this seems like a reasonable place to document it. More importantly, this seems like the mostly likely place future maintainers will look.
Checklist
---------
[docs]: …
> Add a note to CONTRIBUTING.md about publishing to conda-forge

- CHANGELOG.md
- docs/source/noise.rst
The examples folder was moved to a new repo. This PR updates
a link to point to the new repo.
Closes #1175
Checklist
---------
- [ x] The above description motivates these changes.
- [x ] (Bugfix) The associated issue is referenced above using [auto-close keywords][auto-close].
[travis]: …
> Fix broken link to example now in forest-tutorials

- CHANGELOG.md
- pyquil/tests/test_quantum_computer.py
We sometimes narrowly miss the `np.mean(parity) < 0.15` assertion in this test.
See
https://travis-ci.org/github/rigetti/pyquil/jobs/661211565#L1258
Checklist
---------
> Mark test_run as flaky and rerun once on failure

- CHANGELOG.md
- docs/source/basics.rst
- docs/source/noise.rst
- pyquil/quilbase.py
- pyquil/tests/test_gates.py
Description
-----------
Enhancement Controlled gates syntax sugar. Closes #1192.
It seems there is some failure in pyquil/simulation/tests/test_reference_density.py when I tested it locally, seems to be unrelated. I wasn't able to run it on Travis
Checklist
---------
[travis]: …
> Enhancement Controlled gates syntax sugar #1192

- CHANGELOG.md
- pyquil/api/_quantum_computer.py
- pyquil/api/tests/test_quantum_computer.py
- pyquil/tests/test_quantum_computer.py
- pyquil/tests/utils.py
Description
-----------
For `QVM`s based on real devices, `QVM.requires_executable` will be true, which means `QVM.load` will reject non-binary "executables", but will unpack the underlying `Program` object from a `PyQuilExecutableResponse` and save that in `self._executable`.
Since `QuatumComputer.experiment` attempts to re-use the saved executable as long as the experiment hasn't changed, it needs to be re-compiled into a `PyQuilExecutableResponse` again before being handed off to `QVM.load`.
Fixes https://github.com/rigetti/forest-tutorials/issues/2
Respect the declared return type of `AbstractCompiler.native_quil_to_executable` and return a `PyQuilExecutableResponse` from `DummyCompiler.native_quil_to_executable` rather than a bare `Program`.
Checklist
---------
[auto-close]: …
> Fix QuantumComputer.experiment for QVMs that require executables

- CHANGELOG.md
- pyquil/api/_compiler.py
- pyquil/api/_rewrite_arithmetic.py
- pyquil/api/tests/test_rewrite_arithmetic.py
- pyquil/tests/test_api.py
Description
-----------
When compiling native quil programs, the first step is to do "arithmetic rewriting", which turns compound gate parameters into simple memory references. The motivation for this is that the underlying hardware can do a certain amount of arithmetic, but not everything (multiplication and division are done via arithmetic shifts, and so are restricted to powers of two, also real arithmetic is done with fixed point numbers which results in a loss of precision, and so on). 
This arithmetic rewriting is actually quite simple, but presently requires a call to the quilc client. This is a bit annoying, as `native_quil_to_executable` does not otherwise need quilc, and in my personal experience this dependency can be a bit burdensome when developing/testing …
> Add rewrite_arithmetic handler

- CHANGELOG.md
- pyquil/operator_estimation.py
- pyquil/paulis.py
Description
-----------
For Pauli and operator estimation code, there are a few type assertions that can fail. For example, `isinstance(1.0, complex)` is false, since `1.0` is just a float. However, in the Python numeric hierarchy it still supports the usual operations for complex numbers, e.g. `(1.0).real == 1.0` and `(1.0).imag == 0.0`. 
This PR replaces explicit `isinstance` checks on float, complex types with either a check against `numbers.Number` or `numbers.Complex` (the latter specifically when we want to use operations defined for complex numbers.
This wasn't covered by the existing tests, and I don't feel like adding a new one. It came to my attention somewhere in the bowels of `forest-benchmarking` (where a Pauli term got a coefficient of `1.0` -- the horror!).
Checklist …
> Use numeric base classes for type checks

- CHANGELOG.md
- docs/source/advanced_usage.rst
- docs/source/compiler.rst
- docs/source/index.rst
- docs/source/troubleshooting.rst
Description
-----------
Fix some out-of-date information in the compiler docs.
Checklist
---------
> Compiler doc fixes

- docs/source/compiler.rst
Description
-----------
Corrects an omission in https://github.com/rigetti/pyquil/pull/1220, and correctly specifies the default rewiring schema.
> Update Compiler documentation

- CHANGELOG.md
- docs/source/apidocs/gates.rst
- docs/source/basics.rst
- docs/source/compiler.rst
Description
-----------
The doc lists Rigetti native gates, but does not include XY.
Checklist
---------
> Add XY to lists of native gates in docs

- requirements.txt
I guess there was a version change to some library in the readthedocs environment, which ended up causing a dependency mismatch. Bumping the sphinx versions to something more modern (they were rather out-of-date) fixes the readthedocs build.
> Pin sphinx_autodoc_typehints version

- pyquil/api/_config.py
-----------
Okta at times sends back an array rather than string with its OAuth2 tokens. This is causing Pyquil to emit a warning because it type checks the shape. This has no downstream effects of the user so I've taken the scope check out completely.
```
get_qc('Aspen-8')
WARNING - Failed to parse auth token at /home/jovyan/.qcs/user_auth_token.
WARNING - Invalid ['scope'].
WARNING - Failed to parse auth token at /home/jovyan/.qcs/user_auth_token.
WARNING - Invalid ['scope'].
```
Checklist
--------- …
> do not issue warning if scope is array

- CHANGELOG.md
- pyquil/api/_compiler.py
- pyquil/api/tests/data/user_auth_token_invalid.json
- requirements.txt
Description
-----------
Closes #1245
- Clearer error messaging when the QPUCompiler or QVMCompiler times out in network calls
- No hard-coded timeout values of 1 second in connection to `quilc`
- No hard-coded timeout value of 1 second in connection to the translation service (within `HTTPCompilerClient`)
One downside to these changes is that a user may not have `quilc` running correctly, and now must wait for the default value of 10 seconds for the error message explaining that the service is not reachable. Given that this is either/or, it seems clearly better to apply the same user-configurable timeout everywhere (as in this PR) than to hard-code it to 1 second (as on master). This way, users can still work with a `quilc` running under high CPU load.
Checklist
---------
[auto-close]: …
> Make compiler connection check timeout user-configurable

- pyquil/quilbase.py
Description
-----------
Closes #1223. `DefPermutationGate` supported a permutation of type `list` or `np.ndarray` of shape `(N, 1)`. Alas, something like `np.array([0, 1])` wasn't supported because its shape looks like `(N,)`. C'est la vie. Cast to `np.ndarray` early.
Checklist
---------
[travis]: …
> Allow np.array in DefPermutationGate

- .gitlab-ci.yml
- Makefile
Description
-----------
Add pypi push for version releases
Checklist
---------
> Add pypi push to makefile

- pyquil/api/_quantum_computer.py
- pyquil/quilatom.py
- pyquil/tests/test_quantum_computer.py
Description
-----------
`QuantumComputer.run_and_measure` inserts `MEASURE` instructions for all qubits into the program before it is sent for execution by the QPU or QVM. When the target is the QVM this may lead to memory exhaustion: the QVM allocates enough memory to track a wavefunction for the number of qubits used in the program. For a larger number of qubits (around 32), one will use over 1GB of memory which causes the QVM to (rather ungraciously) crash. This PR fixes that by measuring only the qubits used in the program **if and only if** the target is the QVM **and** there is no associated noise model.
Checklist
---------
[changelog]: …
> For noiseless QVMs don't measure all qubits

- LICENSE
This text is supposed to be copied verbatim (as it's instructions for others to apply the license). Otherwise 4a requires copying this form of the license around.
> Use exact text of Apache 2 license

- CHANGELOG.md
- setup.py
Description
-----------
By including a py.typed in the top-level of the package, any packages that depend on pyquil can validate their types against it with mypy.
Checklist
---------
> Add py.typed

- requirements.txt
- setup.py
Since January of this year, antlr has been at version 4.8, and this is now the default version installed by various package managers (e.g. homebrew). I don't see a reason why the PyQuil parser shouldn't use this latest version, but for the sake of visibility I thought I would make this PR rather than pushing changes directly.
> Update ANTLR requirement to >= 4.8

- CHANGELOG.md
- pyquil/api/_compiler.py
- pyquil/api/_qpu.py
- pyquil/paulis.py
- pyquil/pyqvm.py
- pyquil/tests/test_api.py
- pyquil/tests/test_paulis.py
- pyquil/tests/test_paulis_with_placeholders.py
Description
-----------
Addressing issues #1243 and #1267 .
Checklist
---------
> Fix noisy warnings and typing errata

- CHANGELOG.md
- docs/source/compiler.rst
- pyquil/api/_compiler.py
- pyquil/api/_quantum_computer.py
Add a client property to QPUCompiler so that it has better feature
parity with QVMCompiler. Generally we tell folks that
1. QVMCompiler and QPUCompiler should be largely interchangeable,
meaning that you can swap `qc = get_qc("Aspen-8", as_qvm=True)` with
`qc = get_qc("Aspen-8", as_qvm=False)`, and things should Just
Work. And
2. To set the timeout on a QVMCompiler one does
`qc.compiler.client.rpc_timeout = ...` but on a QPUCompiler
`qc.compiler.quilc_client.rpc_timeout = ...`.
This change brings 1 and 2 into alignment, so that the method for
configuring the compiler timeout is the same between the compiler
classes.
Further, it adds a `set_timeout` method for both classes, and updates
the documentation.
> Add quilc_client property to QVMCompiler, improve timeout documentation

- .gitlab-ci.yml
- requirements.txt
Description
-----------
Somehow we've become married to the travis-ci service in the coverage checks. The travis builds are not working (no credits) so the coverage fails, even though we're not that interested in it. Allow it to fail.
Checklist
---------
> Temporarily allow coverage checks to fail

- requirements.txt
- setup.py
Description
-----------
This version introduces support for passing along client-side timeouts
to the server, where the server can then use that timeout to interrupt
jobs.
Checklist
---------
> Bump RPCQ dependency to 3.6.0

- pyquil/_parser/grammar.lark
- pyquil/tests/test_parser.py
Description
-----------
An oddity in the parser was causing lines beginning with the comment character (`#`) to error, though mid-line comments were fine. Easiest solution was just to create a new terminal in the production rules to account for this case.
Checklist
---------
[travis]: …
> Fix parsing all comment types

- pyquil/api/_config.py
Correct a minor typo in a credential-related error message.
> Fix minor typo in error message

- CHANGELOG.md
- pyquil/api/_base_connection.py
- pyquil/api/_qam.py
- pyquil/api/_qvm.py
- pyquil/pyqvm.py
- pyquil/quil.py
- pyquil/tests/test_quil.py
- pyquil/tests/test_qvm.py
Description
-----------
Fixes #1156 where unmeasured memory regions throw a key error when accessed. In particular, this allows one to use `read_memory()` for a declared memory region that has *not* been the target of a measurement. For example, prior to this change, the following was illegal
```
p = Program("DECLARE reg BIT", "X 0") # no measure
qc.run(qc.compile(p))
print(qc.qam.read_memory("reg") # key error
```
However, the same *is* supported for a register named "ro":
```
p = Program("DECLARE ro BIT", "X 0") # no measure
qc.run(qc.compile(p))
print(qc.qam.read_memory("ro") # no key error, empty results
```
Checklist
---------
[changelog]: …
> Add default memory results for all declared regions

- pyquil/external/rpcq.py
- pyquil/external/tests/test_rpcq.py
- pyquil/quantum_processor/transformers/qcs_isa_to_compiler_isa.py
- pyquil/tests/data/compiler-isa-Aspen-8.json
Description
-----------
When Pyquil passes the compiler edges and qubits without gates, the compiler will treat quil on those gates qubits/ edges as valid physical qubits/ edges, but will throw an error when the quil applies an operator to those qubits/ edges (see [comment](https://github.com/rigetti/pyquil/pull/1317#issuecomment-811245645)). Historically, the standard way to deal with these qubits/ edges has been to characterize them as dead in the ISA passed to quilc.
Detailed examples follow in the comments.
A few questions to consider:
* Should the Python client expose the Qubit/ Edge `dead` attribute as something the user can set, or set it when casting to a dictionary and there are no gates present? My preference is the current implementation (I like giving users more flexibility …
> include dead attributes when no gates present

- .github/workflows/commit_syntax.yml
Description
-----------
This simply enforces the commit message syntax used by semantic-release in package.json. There is also a `No code:` option that will by pass any version bump
Checklist
---------
> Fix: add git commit messge check

- poetry.lock
- pyproject.toml
- pyquil/api/_qpu.py
- pyquil/api/_qpu_client.py
- test/unit/conftest.py
- test/unit/test_compiler_client.py
- test/unit/test_qpu_client.py
- test/unit/test_qvm_client.py
- test/unit/utils.py
- `QPUClient` now takes an `EngagementManager` rather than an engagement in its constructor
- `QPUClient` can now do two things:
- On each request, sets the timeout to the lesser of: 1) its originally-configured timeout (from constructor) and 2) the time remaining in the current engagement
- Upon a timeout (which could be due to running into an engagement boundary), retries the request one extra time with a newly-fetched engagement. This should mitigate situations where a request spanned the wall between two contiguous engagements.
> Handle back-to-back engagements

- .github/workflows/test.yml
- .gitlab-ci.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- docs/source/advanced_usage.rst
- poetry.lock
- pyquil/api/_benchmark.py
- pyquil/api/_compiler.py
- pyquil/api/_compiler_client.py
- pyquil/api/_engagement_manager.py
- pyquil/api/_qcs_client.py
- pyquil/api/_qpu.py
- pyquil/api/_qpu_client.py
- pyquil/api/_quantum_computer.py
- pyquil/api/_qvm.py
- pyquil/api/_qvm_client.py
- pyquil/api/_wavefunction_simulator.py
- pyquil/quantum_processor/qcs.py
- scripts/ci_install_deps
- test/e2e/conftest.py
- test/e2e/test_e2e.py
- test/unit/utils.py
- Adds support and e2e tests for concurrency scenarios (multiprocessing, multithreading)
- Adds docs for concurrent usage ([readable version here](https://pyquil--1326.org.readthedocs.build/en/1326/))
- Re-establishes default timeout of 10 seconds (instead of 5) for requests (10 is what pyquil v2 had anyway)
> Concurrency support

- CHANGELOG.md
- docs/source/advanced_usage.rst
- docs/source/compiler.rst
- pyquil/api/_abstract_compiler.py
- pyquil/api/_quantum_computer.py
- test/unit/test_quantum_computer.py
Adds `execution_timeout` to `get_qc()`. Also renames `timeout` back to `compiler_timeout` (as it was in v2).
> Add execution timeout

- CHANGELOG.md
- pyquil/api/_quantum_computer.py
- test/unit/test_quantum_computer.py
Description
-----------
`get_qcs_quantum_processor` initializes QCSQuantumProcessor without a noise model by default, so we throw an error if a user calls `get_qc` with a QPU name and `noisy=True`. 
Checklist
---------
> Throw error on qc with isa and noise

- pyquil/quantum_processor/qcs.py
Description
-----------
Let's not force users to initialize their own configuration when calling `get_qcs_quantum_processor`. 
Checklist
---------
> Provide default conf on get qcs qpu

- poetry.lock
- pyproject.toml
- test/unit/conftest.py
- test/unit/test_api.py
- test/unit/test_compiler_client.py
- test/unit/test_noise.py
- test/unit/test_qpu_client.py
- test/unit/utils.py
Description
-----------
Occasionally an issue will come up in CI where tests will fail trying to bind to ports for running a local RPCQ server. This server was effectively mocking the responses of anyway, so this PR changes techniques to instead patch the RPC client to mock the response earlier.
I know that both @ameyer-rigetti and @kalzoo have suffered from this in, CI, and @ameyer-rigetti is already aware of these changes, so I'm adding you both as reviewers.
One change I'm not totally convinced of is the test to `_calculate_timeout`. Generally I don't like testing internal methods, but checking the timeouts via only public methods requires a lot of setup and introspection which isn't much better. I'd love to get some opinions on the con of testing an internal method vs a much longer …
> Fix: Remove test RPCQ server to improve CI consistency.

- CHANGELOG.md
- pyquil/api/_compiler.py
Replaces `QPUCompiler`'s `calibration_program` and `refresh_calibration_program` with `get_calibration_program(refresh=True/False)`
> Update: improve calibration caching API

- pyquil/api/_quantum_computer.py
Description
-----------
Checklist
---------
> document error on noisy qcs qpu request

- CHANGELOG.md
- docs/source/advanced_usage.rst
- poetry.lock
- pyproject.toml
- pyquil/api/_engagement_manager.py
- pyquil/api/_qpu.py
- pyquil/api/_qpu_client.py
- pyquil/api/_quantum_computer.py
- test/unit/test_engagement_manager.py
- test/unit/test_qpu_client.py
- test/unit/test_quantum_computer.py
- test/unit/test_qvm_client.py
Description
-----------
This PR adds an `endpoint_id` argument to both `QPU` and `get_qc`, as well as support for engagement-to-endpoint within `EngagementManager`.
Checklist
---------
> New: support engagement against a specified quantum processor endpoint

- pyquil/_parser/grammar.lark
- pyquil/_parser/parser.py
- test/unit/test_parser.py
Description
-----------
Checklist
---------
> Fix parse strings with spaces

- CHANGELOG.md
- pyquil/quiltwaveforms.py
See issue #1407: https://github.com/rigetti/pyquil/issues/1407
Description
-----------
Checklist
---------
> Fix: Correctly apply the phase in quilwaveforms

- CHANGELOG.md
- docs/source/start.rst
Description
-----------
This PR removes an extra parentheses which was present in the python code block under Notes in [this section](https://pyquil-docs.rigetti.com/en/stable/start.html#run-your-first-program) of the getting started documentation.
Checklist
---------
[sphinx]: …
> Docs: Fix Python syntax typo in docs/start.rst

- CHANGELOG.md
- pyquil/quantum_processor/transformers/qcs_isa_to_compiler_isa.py
- test/unit/data/compiler-isa-Aspen-8.json
Description
-----------
Assign a fidelity of 100% to RZ operations to break symmetry with RX in ISA.
Closes https://github.com/rigetti/pyquil/issues/1432
Checklist
---------
> Update: Assign a fidelity of 100% to RZ operations to break symmetry with RX in ISA.

- CHANGELOG.md
- docs/source/qvm.rst
- poetry.lock
- pyproject.toml
- pyquil/api/_qam.py
- pyquil/api/_qpu.py
- pyquil/api/_qpu_client.py
- test/unit/test_qpu_client.py
Description
-----------
Provide additional details on `QAMExecutionResult` describing the length of time a program held exclusive hardware access while executing.
Checklist
---------
> Add execution duration to results

- Dockerfile
Description
-----------
Currently, the latest `rigetti/forest` image fails to start `quilc` or `qvm` with the same error seen on Ubuntu in #1434. The fix is simply specifying the version of Debian that comes with the right shared libraries.
Ultimately we will also want to update the qvm and quilc binaries at some point so they work on up-to-date Debian-like distros.
Checklist
---------
[pep-484]: …
> Fix: Docker qvm/quilc in `rigetti/forest` image.

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- pyquil/api/_quantum_computer.py
- test/unit/test_quantum_computer.py
Description
-----------
We want to support the client's ability to execute against a Rigetti QCS QPU using a QCS group account. To this end, we upgrade `qcs-api-client` which will add `X-QCS-ACCOUNT-{ID/TYPE}` headers to outgoing requests when the profile has `account_{id/type}` set.
Supersedes https://github.com/rigetti/pyquil/pull/1438
Checklist
---------
[sphinx]: …
> Support group accounts ii

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Description
-----------
A bug exists in QCS API client when the QCS profile name does not match the credentials name. An upgrade to `0.20.13` fixes this.
Checklist
---------
> Upgrade: qcs-api-client to include credentials name fix

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Description
-----------
Based on #1448, allows using version 0.21.x of `qcs-api-client` with pyQuil.
Checklist
---------
> Upgrade: qcs-api-client to <0.22.0

- poetry.lock
- pyproject.toml
Description
-----------
Checklist
---------
> Docs: Downgrade theme to fix display bug

- scripts/ci_install_deps
This modifies the `scripts/ci_install_deps` script to use the new Poetry installer. This should fix the issues with brownouts in CI:
> This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
You should migrate to https://install.python-poetry.org/ instead. Instructions are available at https://python-poetry.org/docs/#installation.
> A CI environment has been detected! Due to the above deprecation, this installer is subject to an escalating brownout percentage (currently 5%)!
Resolves #1470.
[docs]: …
> chore: use new poetry installer

- docs/source/basics.rst
The example `ccnot_matrix` in the documentation isn't correct; the last row starts with a one when it should be zero.
Closes #1463
~- [ ] All changes to code are covered via unit tests.~
~- [ ] Parameters and return values have type hints with [PEP 484 syntax][pep-484].~
~- [ ] Functions and classes have useful [Sphinx-style][sphinx] docstrings.~
> docs: fix the definition of the ccnot_matrix

- pyquil/api/_engagement_manager.py
> Fix: report non-503 http status errors when creating engagements

- poetry.lock
- pyproject.toml
Update `qcs-sdk-rust` version to improve address lookup for QPU. Closes #1503.
> fix: bump qcs-sdk-version

- pyquil/api/_compiler.py
- pyquil/api/_qpu.py
Our use of pyi types in type annotations is preventing execution. Remove them (for now).
Closes #1505.
> fix: Remove pyi type annotations causing runtime errors

- poetry.lock
- pyproject.toml
Some waveforms were being malformed when serialized. This was fixed downstream. Simply needed to update our pinned `qcs-sdk-python` version.
> fix: bump qcs-sdk-python to fix waveforms

- .github/workflows/prepare-release.yml
Resolves #1525. Knope 0.7.0 contains important fixes to how versions are calculated, which should prevent issues we saw in `quil-rs`.
> ci: update knope to 0.7.0 with version detection fixes

- poetry.lock
- pyquil/quil.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- pyquil/quiltcalibrations.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
- test/unit/test_quilt.py
This PR updates `DefCalibration`, `DefMeasureCalibration`, and `Measurement` such that they are backed by their quil_rs counterparts and uses the `CalibrationSet` API from quil_rs to handle calibrations.
> Use quil_rs for Calibrations

- pyquil/_parser/grammar.lark
- pyquil/_parser/parser.py
- pyquil/quilbase.py
- test/unit/test_parser.py
Add `ENABLE-RAW-CAPTURE` to DefFrame objects.
Closes #1537 
> Add ENABLE-RAW-CAPTURE attribute to DefFrame

- pyquil/quil.py
- pyquil/quilbase.py
- test/unit/test_main.py
- test/unit/test_noise.py
- test/unit/test_numpy.py
- test/unit/test_operator_estimation.py
- test/unit/test_quantum_computer.py
- test/unit/test_quil.py
Turns out we didn't have to touch `get_classical_addresses_from_quil_program` at all because the compatibility layer is doing its job. I did however patch a few holes elsewhere to get it to work. I also took the opportunity to review all the unit tests and update them to reflect their current state. The removal of a `TODO` above a test means that it's passing now, in other cases I updated the comment with more information.
> Re-write `get_classical_addresses_from_quil_program` to use `quil-rs`

- pyquil/quilatom.py
- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilatom.ambr
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilatom.py
- test/unit/test_quilbase.py
Does what it says on the tin, backs the `Frame` and `DefFrame` classes with `quil_rs.FrameIdentifier`, and `quil_rs.FrameDefinition`, respectively.
The original classes were `@dataclass`es. In order to subclass them properly, I removed the `@dataclass` decorator. This may result in unexpected breaking changes. Might be worth labeling it as such, even if we think most of the functionality is the same.
> Back Frame and DefFrame with quil_rs

- poetry.lock
- pyproject.toml
- pyquil/api/_abstract_compiler.py
- pyquil/quil.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- pyquil/quiltcalibrations.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_operator_estimation.py
- test/unit/test_quantum_computer.py
- test/unit/test_quil.py
We can now pickle a `quil-rs` `Program` with [quil-rs#173](https://github.com/rigetti/quil-rs/pull/173). I've updated the tests that were blocked. One passed, the other two are now blocked until we can write memory values to a `quil-rs` `Program`.
Since the PR wasn't much on it's own, I also pointed `qcs-sdk-python` to [this branch](https://github.com/rigetti/qcs-sdk-rust/pull/261), which specifies `quil` as a dependency instead of re-exporting it. I've updated poetry and import paths to match.
> update tests now that a `quil-rs` `Program` can be pickled

- pyquil/paulis.py
- pyquil/quil.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_main.py
- test/unit/test_noise.py
- test/unit/test_numpy.py
- test/unit/test_quilbase.py
Backs `DefGate`, `DefPermutationGate`, and `DefGateByPauli` with `quil-rs`'s `GateDefinition`. The first two were fairly straightforward. `DefGateByPauli` needs [this PR merged](https://github.com/rigetti/quil-rs/pull/177) in `quil-rs`. The `pyquil.paulis` module has no equivalent in `quil-rs`, so we instead convert between the `quil-rs` and `pyQuil` types at the FFI boundary.
> V4 Program API: Back GateDef with GateDefinition

- poetry.lock
- pyproject.toml
- pyquil/api/_benchmark.py
- pyquil/api/_compiler_client.py
- test/unit/test_compiler_client.py
Use the `qcs-sdk-python` implementation of `conjugate_pauli_by_clifford` and `generate_randomized_benchmarking_sequence` from https://github.com/rigetti/qcs-sdk-rust/pull/280. This is breaking because the request/response shapes change.
Release support for lowercase env var names `https_proxy` and `http_proxy` for the client proxy features from https://github.com/rigetti/qcs-sdk-rust/pull/266
> feat!: use qcs-sdk-python implementation of conjugate_pauli_by_clifford and generate_randomized_benchmarking_sequence

- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
This backs `DefWaveform` with quil-rs's `WaveformDefinition`. There was no existing `DefCircuit` instruction, so I created one, also backed by quil-rs, of course.
> V4 Instruction API: DefCircuit, DefWaveform

- pyquil/quilatom.py
- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
Backs `Pragma`, `Reset`, `ResetQubit`, `Fence`, `FenceAll`, `DelayQubits`, and `DelayFrames` with quil-rs.
> V4 Instruction API: Pragma, Reset, Fence, Delay

- pyquil/quil.py
- test/unit/test_quil.py
Quil doesn't have a "headers" concept. `quil-rs`' `to_headers` method was a stop gap that we no longer want to commit to, so we've removed it.
> remove to_headers

- pyquil/_parser/parser.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- pyquil/quiltwaveforms.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
Backs `Capture`, `RawCapture`, and `Pulse`, with their quil-rs counterparts.
Because these instructions take `WaveformReference` and `TemplateWaveform`, I also addressed the compatibility layer for those. For `TemplateWaveform`, this meant stripping it's `@dataclass` decorator, so it's technically a breaking change, but hopefully still backwards compatible for most use cases. Additionally, `TemplateWaveform` can now be more easily used as a waveform invocation using any set of parameters.
> Use quil-rs for Capture, RawCapture, and Pulse

- pyquil/_parser/grammar.lark
- pyquil/_parser/parser.py
- pyquil/quilbase.py
- test/unit/test_parser.py
Add CHANNEL-DELAY attribute to DefFrame objects.
Closes #1565
> feat: Add CHANNEL-DELAY attribute to DefFrame

- pyquil/quilatom.py
- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilatom.py
- test/unit/test_quilbase.py
Re-implements the `Classical` instructions with quil-rs.
> V4: The rest of the non control-flow instructions

- poetry.lock
- pyproject.toml
- pyquil/api/_abstract_compiler.py
- pyquil/api/_compiler_client.py
- pyquil/api/_quantum_computer.py
- pyquil/quil.py
- test/unit/test_compiler_client.py
In v3, the `native_quil_metadata` field on a `Program` was by set when compiling program to native Quil. `qcs-sdk-python` never returned this metadata, so this functionality has been missing in v4.
The [latest release](https://github.com/rigetti/qcs-sdk-rust/pull/291) of `qcs-sdk-python` returns `native_quil_metadata` from `compile_program`. This PR uses that and sets `native_quil_metadata` on the `Program`, just like in v3. I'm marking this as a breaking change, as the class v3 used has been replaced with the `qcs-sdk-python` counterpart. The fields are the same, but it is no longer a dataclass.
> fix!: Set `native_quil_metadata` on `Program` after compilation

- poetry.lock
- pyproject.toml
closes #1583
Related fix in the qcs-sdk here: https://github.com/rigetti/qcs-sdk-rust/pull/305
> V4 fix: native_quil_to_executable will no longer block indefinitely

- pyproject.toml
Fixes https://github.com/rigetti/pyquil/issues/1553
> Loosen `networkx` requirements

- poetry.lock
- pyproject.toml
Bumps `qcs-sdk-python` to 0.8.1 which contains fixes for #1586
> V4 - fix: Parsing parametric DefGate and upper case function call expressions.

- pyquil/api/_qvm.py
- pyquil/api/_wavefunction_simulator.py
This restores things to how they were in v3 - calibrations aren't included in programs sent to the QVM.
> V4- fix: Strip calibrations from QVM requests

- poetry.lock
- pyproject.toml
Relaxing the Python constraints to `^3.8,<4.0`, which just lowers the version of `scipy` in the lock file. IIRC, old versions of `scipy` don't always build nicely on newest versions of Mac OS, but this version works okay on my Intel mac.
> V4: Relax Python version constraint to ^3.8,<4.0

- pyquil/api/_rewrite_arithmetic.py
- pyquil/quil.py
- test/unit/test_quantum_computer.py
Closes #1596 by copying `DECLARE` instructions along with the declarations mapping in `Program.copy_everything_except_instructions()`
> V4 fix: `copy_everything_but_instructions` now correctly copies `DECLARE` statements

- poetry.lock
- pyproject.toml
- pyquil/api/_qvm.py
- pyquil/api/_wavefunction_simulator.py
> V4 - fix: Load defaults for ommitted config fields

- poetry.lock
- pyproject.toml
closes #1607 
I based the version specified on the one that existed in `pyproject.lock`
> V4 - fix: `packaging` is now specified as a dependency

- pyquil/api/_rewrite_arithmetic.py
- pyquil/quil.py
- test/unit/test_quantum_computer.py
Closes #1611 
Refer to the analysis in #1611 for a description of the issue and suggested solution.
The short version is that `Program.declarations` is intended as a view of `Program.instructions`, and should not have been copied in v3. This fix should be back-ported to v3. This MR reverts the earlier changes to resolve the inconsistency the other way; it made the test added in RC23 fail, but then the new approach (don't copy `_declarations`!) also fixed the issue and does not regress in terms of the expectation that `instructions` be empty after `copy_everything_except_instructions()`. …
> 1611 Regression fix for `Program.copy_everything_except_instructions()`

- poetry.lock
- pyproject.toml
- pyquil/api/__init__.py
- pyquil/api/_qam.py
- pyquil/api/_qpu.py
- pyquil/api/_quantum_computer.py
- pyquil/api/_qvm.py
- pyquil/api/_wavefunction_simulator.py
- pyquil/pyqvm.py
Requires that [qcs-sdk-rust#312](https://github.com/rigetti/qcs-sdk-rust/pull/312) is merged and deployed.
> V4: feat!: Use ExecutionOptions parameter to configure how jobs are submitted and retrieved from a QPU

- .github/workflows/test.yml
- .gitignore
- Makefile
- README.md
> V4 - Rework code coverage and re enable in ci

- pyquil/api/_abstract_compiler.py
The `_connect` call got moved up into the initializer, leading to the hang when calling `get_qc` without quilc running. Moved it back into `quil_to_native_quil` where it used to be.
> V4 - fix: Getting a QuantumComputer based on a generic QVM will no longer hang if quilc isn't running

- .github/workflows/release.yml
Removes usage of `${{ env.* }}` context inside the `env` section, because it can only be used in workflows, jobs, or steps.
See https://docs.github.com/en/actions/learn-github-actions/contexts#env-context
> Fix: broken action

- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/programs_and_gates.rst
- docs/source/the_quantum_computer.rst
- docs/source/wavefunction_simulator.rst
What it says on the tin, updating the documentation for the `QuantumComputer` class as well as the section on `WavefunctionSimulator`.
> V4 - docs: Revamp the QuantumComputer and the WavefunctionSimulator sections.

- pyquil/quil.py
- test/unit/test_quilt.py
> V4 - fix: Program#calibrate now returns the original instruction if there was no match

- pyquil/quil.py
closes #1647 
Methodology: Starting with an empty `Program` append a large amount of instructions (~5000) using inplace addition.
| Version | Runtime |
| --- | --- |
| v3.5.4       | 0.0929s |
| v4.0.0-rc.52 | 4.89s |
| This branch  | **0.0642s** |
```python
def generate_program(num_qubits: int, layers: int) -> Program:
program = Program()
params = program.declare("params", "REAL", num_qubits * layers * 3)
idx = 0
for layer in range(layers):
for q in range(num_qubits):
program += RZ(params[idx], q)
idx += 1
program += RX(np.pi / 2, q)
program += RZ(params[idx], q)
idx += 1
program += RX(np.pi / 2, q)
program += RZ(params[idx], q)
idx += 1
return program
def main():
program = generate_program(10, 100)
program.out()
if __name__ == "__main__":
profiler = cProfile.Profile()
profiler.enable() …
```
> V4 - feat: Implement `__iadd__` on `Program`

- pyquil/paulis.py
- pyquil/simulation/matrices.py
- pyquil/simulation/tools.py
- test/unit/test_paulis.py
- Fixes the RYY gate definition #1602 [auto-close]
- Addes a new function in pyquil.paulis called `exponentiate_pauli_sum`. This function performs exponentiation of non-commuting PauliSums, but only for PauliSum with numeric values. The return is a unitary.
- Tests that `exponentiate_pauli_sum` produces the quil gates.
> Fix ryy gate definition

- CHANGELOG.md
- pyquil/quil.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- pyquil/quiltwaveforms.py
- test/unit/test_quil.py
A small bundle of improvements:
1. In `quil`, `Fence` is the only class for `Fence` instructions. When there are no qubits, it should be equivalent to `pyQuil`s `FenceAll`. The difference can be important for users who use something like `isinstance(instr, FenceAll)`. The compatibility layer will now check a `Fence` instructions qubits and return `FenceAll` if it is an empty list.
2. A fix to ensure that all parameters are converted to pyQuil types when building `TemplateWaveform`s in the compatibility layer.
3. Un-deprecate the `TemplateWaveform` classes. These are more important to users that I initially realized, so I've removed the deprecation warning.
4. ~Added a caching layer on `Program` properties after identifying a performance issue in an internal test with repeatedly checking …
> V4 - Cache Program properties, fix compatibility layer for `FenceAll`, `TemplateWaveform`s

- pyquil/quilatom.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
closes #1657 by adding support for quil-rs `FunctionCallExpression`s to the compatibility layer.
> V4 - fix: Handle `quil` FunctionCallExpressions

- pyquil/quil.py
- test/unit/test_quil.py
This was initially part of #1654, but punted until more data was surfaced that suggested we needed it. The caching implemented here reduces the runtime of some benchmarks by multiple minutes.
> feat: cache program properties

- knope.toml
Let knope handle automatically updating our CHANGELOG again.
> re-enable knope changelog management

- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
- test/unit/test_quilbase.py
Closes #1665 
This issue came from `quil` not having an explicit not equals comparison. Bumping `qcs-sdk-python` bumps `quil` to a version with the fix. Recent updates to `quil` should also improve the performance of adding two Program's together.
> fix: `Gate`s should no longer compare as equal and not equal.

- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_numpy.py
- test/unit/test_quilbase.py
Closes #1681. Thanks to @steve-jeffrey for the report and suggested fix!
> fix: The `DefGate.matrix` property will no longer raise an exception when the matrix contains a mix of atomic and object types.

- pyquil/quilbase.py
- test/unit/test_quilbase.py
closes #1674 by overriding `__copy__` and `__deepcopy__` on instruction types that subclass an instruction from the `quil` package.
> fix: Instruction types no longer return a superclass instance when using `copy.deepcopy`

- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
- pyquil/api/_compiler_client.py
- pyquil/quil.py
- test/unit/__snapshots__/test_quil.ambr
- test/unit/test_reference_wavefunction.py
- test/unit/test_rewrite_arithmetic.py
closes #1666, requires rigetti/quil-rs#306 to be deployed and pulled in, but all tests pass locally and this PR is otherwise code complete.
> fix: DefGate's no longer appear in the instructions list

- README.md
- docs/source/advanced_usage.rst
- docs/source/getting_started.rst
- docs/source/introducing_v4.rst
- docs/source/noise.rst
- docs/source/programs_and_gates.rst
> docs: Replace deprecated usage of readout_data with get_register_map

- pyquil/api/_qpu.py
- test/unit/test_qpu.py
> fix: The ``execution_options`` property is now used for retrieving results if no overriding options were provided to the ``execute`` method.

- poetry.lock
- pyproject.toml
- pyquil/api/_qam.py
- pyquil/api/_qpu.py
- test/unit/test_qpu.py
closes #1702
Requires rigetti/qcs-sdk-rust#393 to be deployed.
> feat: Final memory values are now available on QAMExecutionResults

- pyquil/api/_compiler.py
- pyquil/quilbase.py
- test/unit/test_quilbase.py
Closes #1711, but still needs a repro case + test.
I also updated the docstring on `get_calibration_program` to warn about potentially surprising behavior with returning a cached reference.
> fix: DefFrame no longer attempts to serialize HARDWARE-OBJECT as json.

- pyquil/quil.py
- test/unit/__snapshots__/test_quil.ambr
- test/unit/test_quil.py
> fix: Gate instructions specified as tuples no longer error when using a list of parameters.

- pyquil/quilbase.py
- test/unit/test_quilbase.py
> fix: Arithmetic instructions will not raise an error when used in Programs

- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
v4 has added deprecated attribute properties for all the standard defframe attributes, except for CHANNEL-DELAY.  I have a bunch of call sites in my v3 codebase that use this attribute and engineers like to benefit from autocompletion in their IDE when accessing channel delays.  So here is a PR that adds the missing property.
> Add deprecated property to DefFrame for CHANNEL-DELAY attribute

- pyquil/quilbase.py
- test/unit/test_program.py
closes #1726
Thanks to @mac01021 for the report!
> fix: ResetQubit instructions will not be returned as Reset after being inserted into a Program

- pyquil/quilbase.py
- test/unit/test_program.py
> fix: Compatibility layer will prefer to return `DelayFrames`, then `DelayQubits`, then `Delay`.

- pyquil/external/rpcq.py
- readthedocs.yml
- test/unit/test_graph.py
> fix: CompilerISA.dict() now uses the correct default field names: qubits and edges

- docs/source/programs_and_gates.rst
- poetry.lock
- pyproject.toml
- pyquil/api/_qam.py
- pyquil/api/_qpu.py
- pyquil/api/_quantum_computer.py
- pyquil/api/_qvm.py
- pyquil/pyqvm.py
- test/unit/test_qpu.py
> feat: Add execute_with_memory_map_batch method for QPUs

- pyquil/api/_wavefunction_simulator.py
- pyquil/quil.py
- test/unit/test_quil.py
> fix: Program#out(calibrations=False) will not expand calibrations

- pyquil/quilatom.py
- test/unit/test_parameters.py
- test/unit/test_rewrite_arithmetic.py
> fix: The imaginary part of a complex number is no longer moved incorrectly to the outside of a binary expression.

- pyquil/paulis.py
- pyquil/quilatom.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_quilbase.py
Closes #1682.
This implements the numpy array protocol by leaning on quil-rs expression simplification to get a numpy compatible number from the expression, if possible. If not, we still fallback to the default numpy behavior as to not break existing code.
> feat: Expressions without parameters have improved compatibility with numpy.

- pyquil/quilatom.py
- test/unit/test_quilatom.py
> fix: Expression arithmetic does not error when a numpy type is on the left hand side.

- docs/source/advanced_usage.rst
- poetry.lock
- pyproject.toml
- pyquil/quil.py
- test/unit/__snapshots__/test_quil.ambr
- test/unit/test_quil.py
- test/unit/test_rewrite_arithmetic.py
> fix: Program serialization is deterministic, and program equality checks have been corrected.

- poetry.lock
- pyproject.toml
- pyquil/control_flow_graph.py
- pyquil/quil.py
- test/unit/test_control_flow_graph.py
closes #1761 
Needs rigetti/quil-rs#359 to be merged and deployed before for the code in this PR to work in CI.
> feat: Add Program#control_flow_graph() method

- poetry.lock
- pyproject.toml
> fix: Refresh JWT only when expired, not before every request

- pyquil/api/_compiler.py
In the case, of a user making calls from the SDK, there will be a missing client for accessing calibration data. The gRPC requests will fail.
Looking at usage of the qcs-sdk without the client passed in: https://github.com/search?q=repo%3Arigetti%2Fpyquil%20qcs_sdk&type=code
Adding in the client that is passed in to the object (or None as this is optional).
> feat: allow client to be passed in to get qulit calibrations

- poetry.lock
- pyproject.toml
- pyquil/api/__init__.py
- pyquil/control_flow_graph.py
- pyquil/quilbase.py
- test/unit/__snapshots__/test_quilbase.ambr
- test/unit/test_qpu.py
- test/unit/test_quilbase.py
This closes #1719 (along w/ an additional request to support `QPUExecuteResponse`), and #1791 (but for all instruction classes).
Waiting on some upstream changes to land, once they do, this PR should pass CI.
> feat: Instruction classes and execution results now support the pickle module

- pyquil/quilbase.py
- test/unit/test_quilbase.py
closes #1798 
pyQuil v3 defined the `instrs` property on `DefMeasureCalibration` as the only way to get the calibrations contained instructions. The `quil` counterpart uses an `instructions` property for this purpose. In pyQuil v4, we inherit from `quil` base types, but for `DefMeasureCalibration`, never overrode the `instructions` property, meaning that when `instructions` was accessed on `DefMeasureCalibration`, `quil` classes were returned. This fix overrides the inherited instruction property and uses the compatibility layer to return pyQuil compatible instructions.
[pep-484]: …
> fix: The DefMeasureCalibration `instructions` property returns `pyQuil` `AbstractInstrction`s instead of `quil` `Instruction`s

- pyquil/quilbase.py
- test/unit/test_quilbase.py
>  fix: Unpickling an `AbstractInstruction` will result in an `AbstractInstruction` instead of a `quil` `Instruction`

- poetry.lock
- pyproject.toml
Problem: setuptools-77 requires packaging>=24.2.  Installation of pyquil
downgrades packaging to packaging-23 which breaks pre-installed setuptools.
Solution: Let packaging-24 and pyquil coexist in a Python environment.
Example:
```shell
$ pip install "setuptools>=77"
$ python -c "import setuptools" 
$ pip install pyquil
$ python -c "import setuptools"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/t312/lib/python3.12/site-packages/setuptools/__init__.py", line 27, in <module>
from .dist import Distribution
File "/tmp/t312/lib/python3.12/site-packages/setuptools/dist.py", line 15, in <module>
from packaging.licenses import canonicalize_license_expression
ModuleNotFoundError: No module named 'packaging.licenses'
```
[auto-close]: …
> Allow installation of pyquil and packaging-24.2

- Dockerfile
- Dockerfile.test
- poetry.lock
- pyproject.toml
- pyquil/latex/_ipython.py
- pyquil/quilatom.py
- pyquil/quilbase.py
- test/unit/test_qpu.py
From https://github.com/rigetti/pyquil/actions/runs/17415859364/job/49444091708?pr=1833
```
+-------------------------------------+------+-----------+--------------+---------+-------------+
| OSV URL                             | CVSS | ECOSYSTEM | PACKAGE      | VERSION | SOURCE      |
+-------------------------------------+------+-----------+--------------+---------+-------------+
| https://osv.dev/GHSA-33p9-3p43-82vq | 7.3  | PyPI      | jupyter-core | 5.7.2   | poetry.lock |
| https://osv.dev/GHSA-9hjg-9r4m-mvj7 | 5.3  | PyPI      | requests     | 2.32.3  | poetry.lock |
| https://osv.dev/PYSEC-2025-49       | 8.8  | PyPI      | setuptools   | 70.3.0  | poetry.lock |
| https://osv.dev/GHSA-5rjg-fvgr-3xxf |      |           |              |         |             |
| …
```
> fix: update packages with detected vulnerabilities
