README.md, docs/source/getting_started.rst
Added pip installation instructions to *Installation and Getting Started* in the docs and in the README, and tried to be more explicit about the Rigetti Forest vs. QVM distinction and requirements.
=> Added pip installation and cleaned up README

pyquil/quilbase.py, pyquil/tests/test_quil.py
=> handling Qubits in extract_qubits

pyquil/quilbase.py, pyquil/tests/test_quil.py
=> Make .pop return the last instruction and add tests for pop

pyquil/gates.py
Note the definition on line 27.
=> removed duplicate unpack_classical_reg definition

pyquil/parametric.py, pyquil/paulis.py, pyquil/tests/test_paulis.py
* This cleanly separates experimental from prod code
* Decouples grove from experimental code
(see https://github.com/rigetticomputing/grove/issues/20)
=> Removes parametric programs from Paulis

pyquil/quil.py, pyquil/tests/test_quil.py
=> add get_qubits method to pyquil Programs

docs/source/getting_started.rst, examples/meyer_penny_game.py
Minor changes required to getting-started docs for correctness.  Checks
on individual example programs can proceed after I acquire a job queue
key.
=> Minor changes to getting-started docs

pyquil/qpu.py, requirements.txt, setup.py, tox.ini
* Adds tox for build automation (currently only py2.7)
* adds coverage and prints coverage report
* makes small compatibility and PEP8 changes.
=> Toxify build

docs/source/getting_started.rst
interactive should be interaction
=> Typo on line 942

docs/source/examples.rst
=> typo on line 20

docs/source/getting_started.rst, pyquil/job_results.py, pyquil/tests/test_job_results.py
=> Fixed JobResult.is_done to query for update before returning

examples/meyer_penny_game.py, examples/quantum_die.py, examples/teleportation.py
It is using a JobConnection when it should be using a SyncConnection.  A JobConnection would work fine, but it takes extra steps in the docs to introduce this and isn't needed to just test examples.
=> examples are using the wrong connection object

pyquil/setup/config.py
=> Fixed python 2/3 compatibility of pyquil-config-setup script

pyquil/paulis.py, pyquil/tests/test_paulis.py
=> Changing power computation from recursion to iteration

pyquil/paulis.py, pyquil/tests/test_paulis.py
=> raise -> warn in PauliTerm

pyquil/job_results.py
=> fixes bug in job result decoding

pyquil/quil.py, pyquil/quilbase.py, pyquil/tests/test_quil.py
=> Including Instr's in get_qubits

docs/source/getting_started.rst, pyquil/api/job.py, pyquil/api/qpu.py, pyquil/api/qvm.py, pyquil/tests/test_api.py
=> Support cancellation in PyQuil and other connection improvements

pyquil/api/__init__.py, pyquil/api/qpu.py, pyquil/tests/test_api.py
Ability to support multiple QPUs running at the same time.
=> Add get_devices and ability to specify device_name

examples/meyer_penny_game.py, examples/pointer.py, examples/post_rabi.py, examples/post_ramsey.py, examples/post_t1.py, examples/quantum_die.py, examples/run_quil.py, examples/teleportation.py
Since I didn't know how to fix post_rabi.py, post_ramsey.py and post_t1.py, I've deleted them - they would probably be more confusing than helpful for new users.
=> Docs/update examples, fixes #202

pyquil/api/_base_connection.py, pyquil/api/qpu.py, pyquil/api/qvm.py
This functionality was already available in wait_for_job but now it's available in connection methods as well.
=> Add ability to turn off printing status updates and control ping time

pyquil/api/job.py, pyquil/tests/test_api.py
@stevenheidel this introduces some helper functions for accessing the compiler metadata produced by the QPU.
Fixes #214
=> Added helper functions for Job metadata

docs/source/qpu_usage.rst
They don't currently mention when gates are executed.
=> Adding a little bit about how gates are scheduled in the docs.

docs/source/qvm_overview.rst, pyquil/quil.py, pyquil/wavefunction.py
=> Added section on wavefunction ordering to QVM docs

examples/NoiseInvestigation.ipynb, pyquil/kraus.py, pyquil/tests/test_kraus.py
=> Port kraus code from docs and add a high-level interface

LICENSE, pyquil/latex/__init__.py, pyquil/latex/latex_config.py, pyquil/latex/latex_generation.py, pyquil/tests/test_latex.py
Code for generating LaTeX circuits from pyquil Programs. Currently still needs a little bit more code coverage. Input would be appreciated!
=> Latex circuit generation

examples/qaoa_ansatz.py, tox.ini
Resolves #277.
Documentation on the example.
Indentation.
Minor doc fix.
=> QAOA ansatz example (#277)

pyquil/parameters.py, pyquil/tests/test_parameters.py
@stevenheidel this is what I had in mind, what do you think about it?
=> Substitution of Expression parameters and numerical evaluation

pyquil/tests/test_wavefunction.py, pyquil/wavefunction.py
Also ensure normalization and fix tests that weren't normalized
=> Sample from wavefunction

pyquil/api/qpu.py, pyquil/tests/test_api.py
=> Append MEASURE instructions to QPU run_and_measure programs

docs/source/qpu_usage.rst, pyquil/api/qpu.py, pyquil/tests/test_api.py
=> Enable the run functionality on the QPU

pyquil/noise.py
@pkaralekas This should fix the issues you were having.
=> Reduced tolerance for Kraus operator normalization condition

Makefile, pyquil/api/compiler.py, pyquil/api/qvm.py, pyquil/device.py
* Fix device.py _maybe_configure() (Broke in #312)
* Fix iffy circular imports in compiler.py and qvm.py
* Modify makefile so that 'make typecheck' excludes unit tests
=> Fix various type check errors.

docs/source/qpu.rst
It is important that we make this super clear upfront.
=> highlight what qubits are available for programming

docs/source/compiler.rst
Inspired by a question on the Forest Slack channel about how ``CompilerConnection``  works.
=> Added information on how to use CompilerConnection()

tox.ini
=> Run flake8 tests after the actual tests

pyquil/api/qvm.py
=> Improve expectation docs

pyquil/api/compiler.py
This was giving a sphinx warning
=> Docstring formatting

docs/source/compiler.rst
Printing out Eric's compiled program example.
=> Include compiled program output in the docs

docs/source/start.rst
Also put installation instructions *first*
=> Document conda installation

pyquil/api/compiler.py
=> Allow on-the-fly specification of compilation ISA target

pyquil/api/errors.py, pyquil/api/qpu.py, pyquil/api/qvm.py, pyquil/tests/test_api.py
Attempting to close this issue: https://github.com/rigetticomputing/pyquil/issues/179. Should `wavefunction`, `wavefunction_async`, `expectation,` `pauli_expectation` and `expectation_async` also check if the program is empty?
=> Add a condition that checks if a program is empty before running

pyquil/quil.py, pyquil/quilbase.py, pyquil/tests/test_parser.py, pyquil/tests/test_quil.py, pyquil/tests/utils.py
=> adding support for qubitplaceholders to pragmas

docs/source/changes.rst
I've included a short blurb for the changelog about the new compilerconnection endpoints.
=> updating changelog for rb

setup.py
per https://packaging.python.org/guides/single-sourcing-package-version/
Fixes #313
=> Single source version

pyquil/setup/pyquil_config_setup.py
1) try to validate the form of user id and api key and try again if not right
2) make a backup of existing files
fixes #364
=> Robust pyquil-config-setup

docs/source/start.rst
Fix for this: https://github.com/rigetticomputing/pyquil/issues/474
=> Clarify that repo needs to be clone in order to execute run_quil.py

docs/source/changes.rst, docs/source/noise.rst, examples/ReadoutNoise.ipynb, pyquil/_parser/PyQuilListener.py, pyquil/gates.py, pyquil/paulis.py, pyquil/tests/test_device.py, pyquil/tests/test_gates.py, pyquil/tests/test_noise.py, pyquil/tests/test_parametric.py, pyquil/tests/test_parser.py, pyquil/tests/test_paulis.py, pyquil/tests/test_paulis_with_placeholders.py, pyquil/tests/test_quil.py
=> Gates as normal functions

pyquil/quil.py, pyquil/tests/test_quil.py
Fixes #497 and implements tests to cover the issue.
=> Support throwaway MEASURE instructions

pyquil/api/__init__.py
Deleted redudant line 29 "from pyquil.api.compiler import CompilerConnection"
=> 1 line deletion update to __init__.py

MANIFEST
=> Add manifest for readme.md

pyquil/api/compiler.py
Allows user to specify seed when calling generate_rb_sequence. Compiler should already be updated to support this change (although it may need to be redeployed?). Fixes issue #523
=> Added seed argument to generate rb sequence

docs/source/2.0_quickstart_and_migration.rst, docs/source/SDK_Download_Instructions.rst, pyquil/api/_benchmark.py, pyquil/api/_compiler.py, pyquil/api/_qam.py, pyquil/api/_qpu.py, pyquil/api/_quantum_computer.py, pyquil/quil.py, pyquil/tests/test_api.py, pyquil/tests/test_qvm.py, requirements.txt, setup.py
https://pypi.org/project/rpcq/
=> Use rpcQ v1.0.0.dev0 instead of pidgin

pyquil/api/_qpu.py, pyquil/api/_qvm.py
=> Fixup bitstrings -> _bitstrings rename

pyquil/api/_benchmark.py, pyquil/api/_compiler.py, pyquil/api/_qam.py, pyquil/api/_qpu.py, pyquil/api/_quantum_computer.py, pyquil/api/_qvm.py, pyquil/quil.py, pyquil/tests/test_api.py, pyquil/tests/test_qvm.py, requirements.txt, setup.py
`rpcq` is now open sourced! https://github.com/rigetticomputing/rpcq
=> Updates for rpcq 2.0.0

pyquil/api/_compiler.py, pyquil/device.py
mypy pyquil/*.py pyquil/api/*.py pyquil/latex/*.py pyquil/_parser/*.py  --ignore-missing-imports --follow-imports=skip
=> Fix typing errors

pyquil/quil.py, pyquil/tests/test_quil.py
Add updated `validate_protoquil` function, use it for `is_protoquil` method of quil program. add tests.
=> Update protoquil definition / checking

pyquil/api/_qpu.py
=> Fixup bitstrings as ints

pyquil/api/_quantum_computer.py, pyquil/api/_qvm.py, pyquil/tests/test_quantum_computer.py, pyquil/tests/test_qvm.py
=> Potentially realistic compilation behavior

pyquil/tests/test_examples.py
=> Minor fixture scoping bug fix.

setup.py
=> Un-pin reqs in `install_requires`

docs/source/index.rst, docs/source/migration.rst, docs/source/start.rst
Move migration guide to the top level, improve installation half of installation and getting started
=> Improve installation docs

pyquil/api/_base_connection.py, pyquil/api/_config.py, pyquil/api/_devices.py
There are three different endpoints.
fixes #629 
~~need to actually test that this fixes the problem~~ it does
=> Use ForestConnection() for all connections to forest

docs/source/basics.rst, docs/source/migration.rst, pyquil/quil.py
=> Add content to 'Declaring Memory' subheader in programs and gates docs

docs/source/exercises.rst, docs/source/qvm.rst
sorry for the bonus header leveling
=> Move exercise into exercises

docs/source/basics.rst
We actually did do it!
JUST KIDDING bang bang
=> Revert memory_map changes for docs-only 2.0.1 release

docs/source/advanced_usage.rst, docs/source/exercises.rst
I was about to go on a deep dive to recall everything I learned about FFTs, so I think it's best if I open this now
=> Improve QFT exercise

docs/source/advanced_usage.rst
=> Add config file documentation

docs/source/_static/theme_overrides.css, docs/source/advanced_usage.rst, docs/source/apidocs/program.rst, docs/source/basics.rst, docs/source/compiler.rst, docs/source/conf.py, docs/source/index.rst, docs/source/migration.rst, docs/source/modules.rst, docs/source/start.rst, pyquil/quil.py
featuring 
- `Program` and friends
- table wrapping fix .. thanks rackspace documentation
- sprinkling in some xrefs throughout the existing docs
=> Api docs 2

pyquil/quil.py
I know, I know.
I just figured I'd fix this small thing as I was browsing through the code 😄
=> Fixes quil.py comment typo

pyquil/_parser/PyQuilListener.py, pyquil/_parser/Quil.g4, pyquil/_parser/gen3/QuilListener.py, pyquil/_parser/gen3/QuilParser.py, pyquil/tests/test_parser.py
This is in reference to and closes #296
=> Add circuitMeasure and circuitResetState to grammar

pyquil/api/_error_reporting.py
Here's a PR that makes the change you requested. I don't know exactly what you were doing to measure the slowdown, but I'd appreciate it if you could try and see if this fix helps.
Closes #655.
=> skip logging unprotected calls

docs/source/intro.rst
Updating "Introduction to Quantum Computing" page: updated code to be Forest 2.0 compatible (but note a warning msg issued for the while_do(..) code snippet), polished some of the text.
=> Docs intro page

docs/source/intro.rst
@mpharrigan Here's the new PR with just the small change.
=> Fixing while_do(..) to be compatible with recent changes

docs/source/basics.rst
=> Fix broken parametric compilation link

docs/source/wavefunction_simulator.rst
=> Remove extra paren

examples/quantum_die.py
=> Fix quantum die example

docs/source/basics.rst
Fixes #711 (slurpees, anyone?)
=> Document what happens if parameter value is not specified

.gitlab-ci.yml
check it out! we have unit tests running with GitLab CI (just a prototype -- but it works!)
=> Add .gitlab-ci.yml for running unit tests using GitLab CI

.gitlab-ci.yml, pyquil/tests/conftest.py, pyquil/tests/test_api.py
https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#how-to-use-other-images-as-services
=> Add qvm/quilc to the unit tests with gitlab CI services

pyquil/operator_estimation.py, pyquil/tests/test_operator_estimation.py
=> Fix handling of identity in operator estimation

docs/source/changes.rst
=> Update changelog for 2.2.1

pyquil/operator_estimation.py
Makes the json look prettier by using the → character
=> ensure_ascii=False in operator estimation serialization

pyquil/api/_quantum_computer.py, pyquil/tests/test_quantum_computer.py
=> Fix bug mixing flags in get_qc

docs/source/advanced_usage.rst, docs/source/compiler.rst, docs/source/start.rst, pyquil/api/__init__.py, pyquil/api/_benchmark.py, pyquil/api/_compiler.py, pyquil/api/_config.py, pyquil/api/_quantum_computer.py, pyquil/api/_qvm.py, pyquil/tests/conftest.py, pyquil/tests/test_api.py, pyquil/tests/test_qvm.py
This reverts commit af3edaf3330c6a584af447e9d137a2e41f23ed67.
=> Revert "Revert "remove Local variants of QVMCompiler and BenchmarkConnection (#730)" (#781)

pyquil/api/_wavefunction_simulator.py
=> add `memory_map` argument to WavefunctionSimulator calls

README.md, docs/source/index.rst, docs/source/start.rst
Simultaneously fix some broken links.
=> Reference open source repos for QVM and quilc

pyquil/operator_estimation.py
Otherwise python will happily let you iterate using len()
and getitem() which is *not* what you want
=> Define __iter__ for TensorProductState

pyquil/reference_simulator.py
=> skip noise under the correct conditions

pyquil/tests/test_qpu.py
Update test in test_qpu to use SQRT, COS, SIN because the parser requires all caps.
=> Update broken test in test_qpu

examples/run_quil.py
It was out of date, and causing errors during the test suite.
=> Fix examples/run_quil.py

docs/source/intro.rst
foundational issues in the interpretation of quantum states.
Fixes #812
=> Update "An Important Distinction" section to be more careful around open

pyquil/gates.py, pyquil/magic.py, pyquil/quil.py, pyquil/quilbase.py, pyquil/tests/test_latex.py, pyquil/tests/test_parser.py, pyquil/tests/test_quil.py
=> Require classical_reg in Program.measure() and ilk

docs/source/changes.rst, pyquil/__init__.py
Update changelog and bump version.
=> bump version to 2.5.0

pyquil/operator_estimation.py
=> Ensure measure_observables takes as many shots as requested

pyquil/quil.py
=> address_qubits copies original program object

pyquil/quil.py, pyquil/tests/test_quil.py
=> Preserve modifiers during address_qubits()

pyquil/_parser/PyQuilListener.py, pyquil/_parser/Quil.g4, pyquil/_parser/gen3/QuilParser.py, pyquil/tests/test_parser.py
Prior to this, you could not do e.g.
```
MOVE mem[0] -4
```
Closes #918
=> Parse negative numbers in instruction arguments

.github/PULL_REQUEST_TEMPLATE.md, docs/source/changes.rst
This should hopefully be helpful going forward! :)
=> Add a pull request template to the .github directory

.github/PULL_REQUEST_TEMPLATE.md, docs/source/changes.rst, pyquil/__init__.py
=> Release v2.9.0

docs/source/changes.rst, pyquil/api/_compiler.py
=> Relax quilc server requirement when using QVM / pyQVM

README.md
=> Add PyPI & conda version shields.io badges to README

README.md, docs/source/changes.rst
Fixes #947 
Added a Quil code snippet and a more in-depth description of the repository; reorganized and refreshed the content.
=> Clean up and refresh the README

.github/ISSUE_TEMPLATE/BUG_REPORT.md, CHANGELOG.md
Description
-----------
Add a bug report template to pyQuil!
Check out the description of the issue linked below to learn more about what this means.
Fixes #937
=> Add a bug report issue template to pyQuil

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Description
-----------
Add a feature request template to pyQuil, continuing what #985 started.
Checklist
---------
=> Add a feature request issue template to pyQuil

.gitlab-ci.yml, CHANGELOG.md, Makefile, requirements.txt
Description
-----------
Fixes #1011 
Checklist
---------
=> Add a Makefile containing common build operations

CHANGELOG.md, docs/source/noise.rst, examples/ReadoutNoise.ipynb, examples/pointer.py, examples/quantum_die.py, examples/run_quil.py, pyquil/api/_base_connection.py, pyquil/api/_config.py, pyquil/api/_qvm.py, pyquil/api/_wavefunction_simulator.py, pyquil/noise.py, pyquil/paulis.py, pyquil/quil.py, pyquil/quilatom.py, pyquil/quilbase.py, pyquil/tests/test_paulis.py, pyquil/tests/test_paulis_with_placeholders.py, pyquil/wavefunction.py, requirements.txt, setup.py
Description
-----------
Fixes #1057 
Checklist
---------
=> Remove all uses of py2-supporting __future__ and six

.gitlab-ci.yml, pyquil/magic.py, setup.py
Description
-----------
Fixes #1056.
Checklist
---------
=> Support Python 3.8 and include in the CI suite

CHANGELOG.md, entrypoint.sh
Description
-----------
Makes startup faster and reduces noise.
Checklist
---------
=> Redirect qvm/quilc output in the Docker image entrypoint

CHANGELOG.md, pyquil/device/_specs.py
=> Add missing XY values when generating specs from graph

CHANGELOG.md, examples/1.3_vqe_demo.py, examples/quantum_walk.ipynb, examples/requirements.txt
Description
-----------
Collection of small fixes for examples that I noticed while testing All The Things
Checklist
---------
=> Minor fixes for VQE demo and quantum walk examples

CHANGELOG.md, pyquil/experiment/_group.py, pyquil/experiment/tests/test_group.py, pyquil/operator_estimation.py, pyquil/tests/test_operator_estimation.py
Description
-----------
Closes #1031.
Checklist
---------
=> Add helper to separate ExperimentResults

CHANGELOG.md, mypy.ini, requirements.txt, setup.py
Description
-----------
Reason: https://github.com/conda-forge/pyquil-feedstock/issues/40
Checklist
---------
=> Pin antlr4-python3-runtime to under 4.8

ACKNOWLEDGEMENTS.md, CHANGELOG.md
Description
-----------
Fixes #1015 
Checklist
---------
=> Expand upon the acknowledgements file

.gitlab-ci.yml, CHANGELOG.md, Makefile, README.md, requirements.txt
Description
-----------
Also adds `coveralls` for code coverage.
Fixes #1024 and fixes #955 
Checklist
---------
=> Another round of README cleanup and improvements

README.md
Description
-----------
The paper has been published!
https://dx.doi.org/10.1088/2058-9565/ab7559
Time to update the citation :)
=> Update QCS paper citation and links for journal publication

pyquil/_parser/PyQuilListener.py, pyquil/quil.py, pyquil/quilatom.py, pyquil/quilbase.py, pyquil/quiltwaveforms.py, pyquil/tests/test_parser.py, pyquil/tests/test_quilt.py, requirements.txt, setup.py
Description
-----------
This updates some of the proposed Quilt AST code, including explicit template waveform classes.
=> Update Quilt AST

pyquil/device/_isa.py
Closes https://github.com/rigetti/quilc/issues/640
=> Add `RX(0) _` to the native gates of a N-q qvm

pyquil/experiment/_main.py
Remove some f-strings that didn't need to be f-strings, to appease flake8.
=> quell flake8 h8

CHANGELOG.md, docs/source/noise.rst, pyquil/noise.py, pyquil/tests/test_noise.py
Description
-----------
Fixes the damping after dephasing noise model; see #1217.
Checklist
---------
=> Noise model fix

pyquil/api/_rewrite_arithmetic.py, pyquil/paulis.py
Fix type checking. I have added the `check-types` target to semaphore, which should keep semaphore and gitlab in sync. I will make a bug fix release after this to get a new pyquil docker image up.
=> Fix check types

docs/source/compiler.rst
Description
-----------
Checklist
---------
=> Expand / improve the rewiring section in the compiler docs

pyquil/quil.py, pyquil/tests/test_quilt.py
Address https://github.com/rigetti/pyquil/pull/1257#discussion_r511203230 and https://github.com/rigetti/pyquil/pull/1257/files/4d00f5ce31b9582eb4f58916f60460a6f91c4187#r511203346
=> Quilt adding programs

pyquil/api/tests/test_base_connection.py, pyquil/api/tests/test_compiler.py
A lingering frustrating from `UserMessageError`.
=> Fix qpu url quilt error

CHANGELOG.md, pyquil/wavefunction.py
Closes #1275 
H/T @mhodson-rigetti
=> Efficient unpacking of bitstring

CHANGELOG.md, pyquil/_parser/parser.py, pyquil/tests/test_parser.py
Fixes #1295 by mapping `Parameter`s to strings
=> Fix parameterized DEFCIRCUITs

.github/workflows/test.yml, .gitlab-ci.yml, Makefile, scripts/ci_install_deps
Correct workflow so that checks run on PRs to RC branch
=> Fix: GitHub checks for PRs to rc branch

poetry.lock, pyproject.toml, pyquil/api/_qam.py, pyquil/api/_qpu.py, pyquil/api/_quantum_computer.py, pyquil/api/_qvm.py, pyquil/api/_wavefunction_simulator.py, pyquil/experiment/_result.py, pyquil/noise.py, pyquil/operator_estimation.py, pyquil/paulis.py, pyquil/pyqvm.py, pyquil/quilatom.py, pyquil/simulation/_numpy.py, pyquil/simulation/_reference.py, pyquil/simulation/matrices.py, pyquil/simulation/tools.py, pyquil/wavefunction.py
Bumps numpy and satisfies mypy
=> Update numpy to ^1.20

pyproject.toml
Description
-----------
Just a simple rc bump to get the compiler argument fixes out.
=> bump release candidate version

.github/workflows/commit_syntax.yml, pyquil/quantum_processor/transformers/qcs_isa_to_compiler_isa.py
Description
-----------
Fixes a bug that maps CPHASE to iSWAP gate when converting QCS ISA to Quilc ISA.
=> Fix cphase gate info

.github/workflows/test.yml, .gitlab-ci.yml, CHANGELOG.md
Adds Python 3.9 to testing matrices
=> Support python 3.9

CHANGELOG.md, pyquil/quantum_processor/transformers/qcs_isa_to_compiler_isa.py, test/unit/conftest.py, test/unit/data/compiler-isa-Aspen-8.json
Description
-----------
Checklist
---------
=> Pass rx rz fidelity w sim frb

.gitlab-ci.yml
=> Make test publishes optional

poetry.lock, pyproject.toml
Closes #1440
I tried to update Sphinx as well but it fails with cross-linking errors which are notoriously hard to solve so... we'll be saving that for another time.
=> Chore: Update some dependencies

poetry.lock, pyproject.toml, pyquil/api/_abstract_compiler.py, pyquil/api/_compiler_client.py, test/unit/conftest.py, test/unit/test_compiler_client.py
=> get quilc version info from qcs sdk

pyquil/quantum_processor/transformers/qcs_isa_to_compiler_isa.py
This small change substitutes the exception path if 1Q simultaneous RB values are not available, and uses the default fidelities for RX gates instead. These default fidelities were already coded in the updated module but were not referred to.
Closes #1555 
=> Fix: Allow benchmarks to be missing for 1QRB; fallback to default RX fidelity

poetry.lock, pyproject.toml
=> feat: increase gRPC message size limit

.github/workflows/release.yml
Related to #1641 re-closes #1640
=> Fix: broken action pt 2 (vars is not env context)

poetry.lock, pyproject.toml
Pull in changes and fixes from qcs-sdk-rust and quil-rs.
=> feat: update qcs-sdk-rust

docs/source/the_quantum_computer.rst
Closes #1686 
- Update links where there is a direct analog
- Remove links that don't have a great analog
=> chore: fix broken docs link

poetry.lock, pyproject.toml
=> fix: Relax numpy and scipy requirements

pyquil/quilbase.py, test/unit/test_quilbase.py
=> feat: Add `get_attribute`, `set_attribute` `__getitem__` and `__setitem__` methods to `DefFrame`

docs/source/programs_and_gates.rst, docs/source/quilt.rst, poetry.lock, pyproject.toml, pyquil/quil.py, test/unit/test_program.py
=> feat: Add utility for filtering Programs and a method for removing Quil-T instructions

docs/source/advanced_usage.rst
=> docs: Example of using control flow to create a sentinel-based loop

.github/workflows/release-dry-run.yml, .github/workflows/test.yml
=> ci: Resolve permission issue with release dry run and coverage reporting

test/unit/test_program.py
=> Fix Delay in test

.github/workflows/test.yml
This should hopefully resolve the permissions issue current blocking CI in #1738.
=> ci: Add content read permission to coverage step
